[Step1-3] 스프링 쇼핑몰 기능 구현
next-step/spring-shopping-old pull request #13
Opened 2023-08-03 14:55 UTC by rimrim990

안녕하세요! 우테캠 박예림입니다.
스프링 쇼핑몰 미션 3단계까지 구현 완료하여 리뷰 요청 드립니다.

## 기능 구현

### Step1
- 상품 목록 조회 기능 구현

### Step2
- 로그인 기능 구현, jwt `accessToken` 반환
- 로그인 사용자 `accessToken`으로부터  사용자 id 를 가져오는 기능 구현 (argumentResolver, interceptor)

### Step3
- 장바구니 CRUD 구현

질문 사항은 댓글로 남기도록 하겠습니다.
감사합니다 !! 😊

2023-08-03 15:30 UTC, rimrim990 commented on src/main/java/shopping/application/CartProductService.java
> +                .orElseThrow(() -> new ProductException("상품Id에 해당하는 상품 존재하지 않습니다"));
기능을 구현하다보면 비슷한 오류 메세지를 갖는 경우가 많은데, 시스템 규모가 클 때 이를 효과적으로 관리할 수 있는 방법이 궁금합니다!
별도로 분리하면 중복은 줄일 수 있지만, 다른 파일로 한 번 더 이동해야 하니깐 직관적으로 이해가 가지 않을 것 같아서 별도 파일로 분리할지 고민이 됩니다.

2023-08-04 15:06 UTC, Laterality requested changes
안녕하세요.

잘 구현해주셨네요.

남겨드린 코멘트 확인해주세요.

추가로 일부 테스트가 실패하고 있는데, 함께 확인해주세요.

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/application/CartProductService.java
> +                .orElseThrow(() -> new ProductException("상품Id에 해당하는 상품 존재하지 않습니다"));
트레이드오프라고 할 수 있겠네요. 중복이 많지 않다면 오히려 메시지를 중복하는 편이 코드를 이해하기 직관적일 수도 있고, 중복이 늘어나거나 메시지에 대한 다국어 처리가 필요하다면 메시지를 분리하는 게 나을 수도 있고요.

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
1. 단일 결과를 반환하는 메서드인데 `getResultList()`를 사용할 필요가 있을까요?
2. `stream.findAny()` 대신 `Optioonal.ofNullable()`을 사용하면 어떨까요?

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/domain/Member.java
> +    public boolean matchPassword(String password) {
👍

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/domain/Product.java
> +    }
기본 생성자가 필요할까요?

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
필요한 어노테이션일까요?

2023-08-04 15:06 UTC, Laterality commented on src/main/java/shopping/utils/EmailUtils.java
> +public class EmailUtils {
유틸리티 클래스 대신 VO로 만들면 어떨까요?

2023-08-04 15:06 UTC, Laterality commented on src/test/java/shopping/application/CartProductServiceTest.java
> +            assertThat(exception).isNull();
예외만 던지지 않으면 장바구니에 추가됐다고 볼 수 있을까요?

2023-08-05 14:51 UTC, rimrim990 commented on src/main/java/shopping/application/CartProductService.java
> +                .orElseThrow(() -> new ProductException("상품Id에 해당하는 상품 존재하지 않습니다"));
상황을 고려해 판단해야 하는 사항이군요. 감사합니다 !

2023-08-05 15:53 UTC, rimrim990 commented
> 안녕하세요.
> 
> 잘 구현해주셨네요.
> 
> 남겨드린 코멘트 확인해주세요.
> 
> 추가로 일부 테스트가 실패하고 있는데, 함께 확인해주세요.

안녕하세요. 리뷰 감사드립니다 ! 
`application.properties` 에 jwt 토큰 생성을 위한 비밀키를 만들어두었는데, 이를 커밋하지 않아서 그런 것 같습니다. 
추가하도록 하겠습니다 ~!

2023-08-06 12:36 UTC, rimrim990 commented on src/main/java/shopping/domain/Product.java
> +    }
네 ! 엔티티에 기본 생성자가 존재하지 않으면 인텔리제이에서 에러를 발생시킵니다.
<img width="403" alt="스크린샷 2023-08-06 오후 9 30 09" src="https://github.com/next-step/spring-shopping/assets/62409503/b6a3f4de-501a-4a1f-a5ec-cabd96c81a72">

질문 해주신 김에 왜 필요한지 디버깅해보았는데, `JPA` 에서 지연로딩된 객체를 초기화 할 때와 쿼리 조회 결과로부터 엔티티 객체를 생성할 때 기본 생성자가 사용되고 있었습니다 !

2023-08-06 13:39 UTC, rimrim990 commented on src/test/java/shopping/application/CartProductServiceTest.java
> +            assertThat(exception).isNull();
생성 여부를 확인할 수 있도록 테스트를 더 구체화하도록 하겠습니다 !

2023-08-06 15:24 UTC, rimrim990 commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
스프링에서 `@RequestBody` 로 역직렬화 할 때, `LoginRequest` 생성자에 작성한 검증 로직이 실행되게 하려고 작성하였습니다 !

`@JsonCreator` 를 사용하지 않으면 objectMapper 가 기본 생성자를 사용하여 dto 를 생성하기 때문에, dto 검증이 실행되지 않아서 추가했습니다.

2023-08-06 15:55 UTC, rimrim990 commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
말씀하신 대로 단건 조회 시에 `getResultList` 로 모든 결과를 처리하는 것은 비효율적일 것 같습니다 !

[cfff75a](https://github.com/next-step/spring-shopping/pull/13/commits/cfff75abdff15cdd393e52dd3e14284c0f797c92)
찾아보니 `getSingleResult` 라는 메서드가 있어 이것을 적용해보았습니다.  그런데 해당 메소드를 사용하면 result 가 없을 때 에러를 발생시킵니다. 그러나 현재 시스템에서는 result 가 존재하지 않아도 에러 상황이 아니기 때문에, 이를 감싸기 위한 `try-catch` 블록과 `Optional` 처리로 인해 메서드가 지저분해진 것 같습니다.

또한 이전에 `catch` 블록에서 값을 리턴하는 것은 예측 불가능한 코드이기 때문에 지양해야 한다고 들었었는데, 더 좋은 방법이 생각나지 않아 일단 이렇게 구현하였습니다 !

2023-08-06 15:57 UTC, rimrim990 commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
[8bd01d3](https://github.com/next-step/spring-shopping/pull/13/commits/8bd01d3b14d5562d5151b9beed4f48383469100e)

메서드를 깔끔하게 리팩토링 하고 싶어서 더 고민해봤는데, 차라리 위와 같이 `getMaxResult(1)` 을 추가하여 db에서 한 건만 가져오도록 하는 건 어떨까요 ?

2023-08-06 16:01 UTC, rimrim990 commented on src/main/java/shopping/utils/EmailUtils.java
> +public class EmailUtils {
좋은 의견 감사드립니다 ㅎㅎ 👍

2023-08-06 16:12 UTC, rimrim990 commented on src/main/java/shopping/utils/EmailUtils.java
> +public class EmailUtils {
VO 로 바꾸는 과정에서 고민되는 지점이 생겼는데, 리뷰어님의 의견을 듣고 싶어 질문 드립니다 !

DTO 로 받아온 원시 값을 VO 로 변환하는 책임은 어디에 둬야할지 고민이 됩니다.
현재는 `service` 계층에서 원시 값을 `Email` VO 로 변환하고 있습니다. (ex. `AuthService.login`)
- `DTO` 는 계층 사이 값만 전달하는 객체라고 생각해서 도메인인 `VO` 를 생성하는 책임을 갖는 건 부적절하다고 생각했습니다.
-  `repository` 는 외부 시스템인 DB 와 연결하는 역할을 수행한다고 생각해서 여기도 부적절하다고 생각했습니다.
그래서 남은 곳이 `service` 라서 `service` 계층에 넣어주었습니다.

그런데 만약 `Email` VO 를 필요로 하는 서비스가 많아진다면, `DTO` 로 받은 원시 값을 VO 로 변환해주는 로직이 여러 서비스에 흩어질 것 같습니다. 그렇기 때문에 애초에 `DTO` 에서 변환해서 서비스에 넘겨준다면 중복이 줄어들지 않을까 하는 생각도 들었습니다. 그렇지만 `DTO` 에서 도메인인 `VO` 를 포함하는 게 어색한 느낌도 드네요 ㅎㅎ

리뷰어님께서는 어떻게 생각하시는지 여쭤보고 싶습니다 ! 감사합니다.

2023-08-07 00:10 UTC, Laterality requested changes
피드백 잘 반영해주셨습니다.

질문 남겨주신 부분에 몇 군데에 추가로 코멘트 남겨드렸습니다. 확인 부탁드려요.

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/utils/EmailUtils.java
> +public class EmailUtils {
경우에 따라 다를텐데요. 변환이 필요한 곳이 지금처럼 서비스 한 군데 뿐이라면 서비스 내에서 변환을 처리하는 것도 방법이 될 수 있고, 그렇지 않다면 DTO나 VO 중 한군데서 처리할 수밖에 없겠네요.

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
선언되지 않은 생성자를 사용할 수는 없을텐데요. 어노테이션을 제거해도 테스트가 모두 통과하는데, 해당 케이스를 테스트하신 코드가 있을까요?

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
> 그러나 현재 시스템에서는 result 가 존재하지 않아도 에러 상황이 아니기 때문에

이 부분은 비즈니스 로직에 의한 규칙으로 보이는데요. repository를 호출하기 전에 서비스나 도메인에서 검증해야 하지 않을까요?

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/application/CartProductService.java
> +    public static final int MIN_CART_PRODUCT_QUANTITY = 1;
내부에서만 쓰이는 상수는 `private`으로 선언하면 어떨까요?

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/ui/advice/GlobalControllerAdvice.java
> +public class GlobalControllerAdvice {
아래 세 가지 예외를 제외한 나머지 `Exception`들은 어떻게 응답할까요?

2023-08-07 00:10 UTC, Laterality commented on src/main/java/shopping/ui/argumentresolver/LoginArgumentResolver.java
> +        return request.getAttribute("memberId");
`getAttribute`가 null을 반환하면 어떻게 될까요?

2023-08-07 04:55 UTC, rimrim990 commented on src/main/java/shopping/ui/advice/GlobalControllerAdvice.java
> +public class GlobalControllerAdvice {
`@ExceptionHandler` 에서 처리되지 않은 예외들은 서블릿으로 넘어가기 때문에 사전에 정의한 `ErrorResponse` 와 다른 형태로 반환되는 군요 !
다른 예외들도 처리될 수 있도록 `@ExceptionHandler` 를 추가하도록 하겠습니다 !

2023-08-07 05:07 UTC, rimrim990 commented on src/main/java/shopping/ui/argumentresolver/LoginArgumentResolver.java
> +        return request.getAttribute("memberId");
로그인하지 않은 사용자가 `@Login` 을 사용하면 안되므로, 별도의 에러 처리를 해줘야 겠군요 ! `LoginArgumentResolver` 의 검증 로직을 추가하도록 하겠습니다.

2023-08-07 05:33 UTC, rimrim990 commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
네 ! [e62081d](https://github.com/next-step/spring-shopping/pull/13/commits/e62081d416db5a7f9906e2bca0b19aea5b91b42b) 에 추가된 메서드에서 테스트하고 있습니다.
- AuthIntegrationTest.returnBadRequest_WhenEmailIsBlank
- AuthIntegrationTest.returnBadRequest_WhenPasswordIsBlank
- CartProductIntegrationTest.returnBadRequest_WhenQuantityIsNegative

`@JsonCreator` 를 사용하지 않으면 역직렬화 시 기본 생성자를 사용하기 때문에 테스트를 통과하지 못했습니다.

> 선언되지 않은 생성자를 사용할 수는 없을텐데요. 

이 부분은 어떤 걸 말씀하시는 건가요 ?!

2023-08-07 06:32 UTC, rimrim990 commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
에러 상황이 아니라는 판단은 비즈니스 로직에 의한 규칙이기 때문에 서비스나 도메인에서 `try-catch` 를 해줘야 한다는 말씀이실까요 ?
이해한 내용을 토대로 아래와 같이 수정해보았습니다 !

[refactor: db 조회 결과가 존재하지 않을 때, service 에서 에러 상황으로 판단하지 않도록 수정](https://github.com/next-step/spring-shopping/pull/13/commits/725ee81fc38d93d19e59088de680602aff6148f4)
- `repository` 계층에서 조회 결과가 없을 시 던져지는 `NoResultException` 을 도메인 예외로 감싸서 `throw`
- `service` 계층에서는 예외 발생 시, 정상 처리하도록 `try-catch` 블록으로 `repository` 호출부를 감싼다

2023-08-07 06:36 UTC, rimrim990 commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
`@RequestBody` 생성을 위해 메세지 컨버터에서 역직렬화 수행 시, `CartProduct` 생성자에서  `CartExcpetion` 을 던지면 그대로 던져저서 `CartExceptionHandler` 에서 처리될 줄 알았는데, `RuntimeExceptionHandler` 에서 처리되네요 !

역직렬화 실패 시 발생하는 에러를 처리할 수 있도록 `HttpMessageNotReadableException.class` 예외 처리 메서드를 추가하였습니다.

[생성 실패 시, RuntimeException 으로 처리되지 …](https://github.com/next-step/spring-shopping/pull/13/commits/a414746e73e298c93b6fc79f1f4f2e4c4ca06db0)

2023-08-07 12:46 UTC, Laterality approved these changes
피드백 잘 반영해주셨습니다.

이번 단계는 이만 머지하도록 하겠습니다.

남겨드린 코멘트는 다음 단계 진행하시면서 참고해주세요.

2023-08-07 12:46 UTC, Laterality commented on src/main/java/shopping/dto/request/LoginRequest.java
> +    public LoginRequest(@JsonProperty String email, @JsonProperty String password) {
요청 객체의 역직렬화 문제는 컴파일러 문제일텐데요.

IntelliJ 설정 -> **Build, Execution, Deployment** -> **Build Tools** -> **Gradle**에서 **Build and run using**과 **Run tests using** 항목을 확인해보세요. 만약 IntelliJ로 돼 있다면 아래 두 가지 중 하나를 적용한 뒤 프로젝트 재빌드 후 테스트를 실행해보세요.

1. 두 항목을 Gradle로 변경
2. IntelliJ 설정 -> Build, Execution, Deployment -> Compiler -> Java Compiler -> Additional command line parameters에 `-parameters` 추가

이와는 별개로 프로퍼티 생성자만 있으면 RestAssured에서 역직렬화를 못하고 있는데요. 이 문제는 json path만 사용하거나 `@JsonCreator` 어노테이션을 붙일 수밖에 없겠네요.

요구사항에 크게 연관된 내용은 아니라 참고만 하고 넘어가셔도 좋습니다.

2023-08-07 12:46 UTC, Laterality commented on src/main/java/shopping/repository/CartProductRepository.java
> +                .findAny();
네 맞습니다. 영속성 계층에서 예기치 못한 결과(e.g. 반드시 하나만 존재해야 하는 결과가 0개 또는 둘 이상인 경우)가 발생할 수는 있지만 이런 상황이 발생하지 않도록 하거나 발생한 경우에 대한 처리는 영속성 계층의 책임은 아니라고 보여요.

2023-08-07 12:47 UTC, merged