Step4, 5 구현 완료하였습니다.
next-step/spring-shopping-old pull request #23
Opened 2023-08-09 12:54 UTC by bkRyusim

안녕하세요! 항상 리뷰해 주셔서 감사합니다😊

### 변경 사항
- Order 기능을 추가하였습니다. OrderItem은 Value Object로 정의하였고, ElementCollection을 이용해 참조합니다.
- config 패키지를 ui 아래로 이동했습니다.
- 환율 API를 받아오는 객체를 생성하고, 인터페이스를 application 패키지에 두어 application이 infrastructure를 의존하지 않게 하였습니다.
- 환율 API 키는 별도 currencylayer-api.properties 파일에 분리하고, gitignore 처리하였습니다.

### 질문
- 저번에 TokenProvider가 왜 application 패키지에 있냐고 질문해 주셨는데, AuthService에서 토큰을 생성하기 떄문에 TokenProvider 인터페이스를 application패키지에 두어 infrastructure를 의존하지 않게 하기 위함이었습니다. 혹시 도메인 레이에서 처리하도록 도메인 패키지까지 내려야 한다는 의도의 리뷰였던건지 궁금합니다!
- 외부 API를 호출하는 로직이 트랜잭션 메서드 안에 있어도 될까요? Cart를 조회하는 것, api에서 환율을 조회하는 것, Order를 생성하는 일련의 과정을 하나의 원자적 단위로 보고, 어느 하나가 실패하든 롤백하도록 하기 위해 한 메서드에서 DB 조회, 검증, API 요청, DB 삽입을 처리했습니다. 그런데 Lock을 걸게 되면, 한 트랜잭션으로 묶자니 api 응답시간동안 락을 점유하여 자원이 낭비되는 것이 아닌가 걱정도 됩니다.

2023-08-10 11:32 UTC, begaonnuri requested changes
안녕하세요 승윤님, 이번 단계도 잘 구현해주셨네요.
몇가지 코멘트 남겼는데 확인해주세요.

2023-08-10 11:32 UTC, begaonnuri commented on .gitignore
> +src/main/resources/currencylayer-api.properties
API키 값때문에 분리해주신걸까요? 👍🏻 

이런 경우 환경 변수를 설정하고 properties 파일에서 이를 가져와 사용하는것이 더 좋을 것 같아요.

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/application/ExchangeRateProvider.java
> +}
외부 API를 사용하는 부분을 인터페이스로 잘 분리해주셨네요 👍🏻

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/application/OrderService.java
> +        double exchangeRate = exchangeRateProvider.getExchangeRate()
질문 주신 내용처럼 트랜잭션의 시간에 외부 API 요청시간이 포함되어 길어지겠네요. 이 부분을 분리해보면 어떨까요? 다양한 선택지가 있을 것 같은데 선택하신 이유도 함께 남겨주시면 좋을 것 같네요 👍🏻

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/application/OrderService.java
> +        Order order = orderMapper.mapOrderFrom(cart, exchangeRate);
매핑을 분리해주셔서 서비스 레이어의 가독성이 올라갔네요 👍🏻

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/domain/cart/CartItem.java
> +    @ManyToOne(fetch = FetchType.EAGER)
fetch 방식을 변경하신 이유가 있을까요?

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/domain/order/OrderItem.java
> +    private Price price;
지금은 Order와 Product의 가격이 동일하겠지만 예를들어 쿠폰같은 개념이 생긴다면 장바구니 아이템의 가격이 주문 가격과 다른 개념이 될 수도 있습니다. 

아직 이런 요구사항이 없으니 특화된 모델 이름을 사용하진 않아도 되지만 패키지라도 구분해야 나중에 명확하게 구분이 가능하지 않을까요?

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/domain/wrapper/Image.java
> +@Access(AccessType.FIELD)
따로 지정해주신 이유가 있을까요?

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/infrastructure/CurrencyLayerExchangeRateProvider.java
> +                .build();
너무 많은 일이 이루어지는 것 같아요. WebClient는 `@Bean`을 통해 외부에서 설정하면 어떨까요?

2023-08-10 11:32 UTC, begaonnuri commented on src/main/java/shopping/infrastructure/CurrencyLayerExchangeRateProvider.java
> +        return webClient.get().uri(builder -> builder.path(EXCHANGE_RATE_API_PATH)
일시적인 네트워크 오류로 환율 정보를 가져오지 못하면 주문이 실패하게 될텐데 사용자 경험이 좋지 않을 것 같아요. retry를 활용해보면 어떨까요?

2023-08-10 11:32 UTC, begaonnuri commented on src/test/java/shopping/dto/OrderItemResponseTest.java
> +class OrderItemResponseTest {
DTO까지 테스트해주신 점도 좋지만, 테스트도 결국 유지보수의 대상이기도 해요. 별다른 로직이 없이 변환만 하는 테스트는 의미가 없기도 하고 추후 기술 부채로 다가올 수도 있어요.

2023-08-10 11:32 UTC, begaonnuri commented on src/test/java/shopping/infrastructure/FakeExchangeRateProvider.java
> +public class FakeExchangeRateProvider implements ExchangeRateProvider {
Fake 객체를 잘 활용해주셨네요 👍🏻

2023-08-10 11:32 UTC, begaonnuri commented on src/test/java/shopping/infrastructure/FakeExchangeRateProvider.java
> +@Profile("test")
매번 profile을 설정하는것이 번거로울 것 같아요. 테스트용 application.properties에서 지정하면 어떨까요?

2023-08-13 02:39 UTC, bkRyusim commented on src/main/java/shopping/domain/cart/CartItem.java
> +    @ManyToOne(fetch = FetchType.EAGER)
장바구니를 조회할 때 어차피 Product에 관한 모든 정보가 필요해서 Join 쿼리 한번으로 필요한 정보를 얻도록 EAGER로 변경했습니다. 혹시 이런 경우에도 EAGER로 사용하면 부작용이 있을까요?

2023-08-13 02:42 UTC, bkRyusim commented on src/main/java/shopping/domain/wrapper/Image.java
> +@Access(AccessType.FIELD)
OrderItem을 Entity로 정의하지 않고 VO로 정의하고, Order에서 ElementCollection을 이용해 참조하고 있습니다. 이 때 AccessType을 FIELD로 하지 않으면 PropertyNotFoundException(Could not locate setter method for property [shopping.domain.wrapper.Image#image]) 이 발생해 AccessType을 설정해 주었습니다.

2023-08-13 02:42 UTC, bkRyusim commented on src/main/java/shopping/infrastructure/CurrencyLayerExchangeRateProvider.java
> +                .build();
적용해 보겠습니다!

2023-08-13 02:58 UTC, bkRyusim commented on src/test/java/shopping/dto/OrderItemResponseTest.java
> +class OrderItemResponseTest {
앞으로 개발할 때 참고하겠습니다 감사합니다! ☺️

2023-08-13 02:59 UTC, bkRyusim commented on .gitignore
> +src/main/resources/currencylayer-api.properties
네 적용해 보겠습니다!

2023-08-13 13:18 UTC, bkRyusim commented on src/main/java/shopping/infrastructure/CurrencyLayerExchangeRateProvider.java
> +        return webClient.get().uri(builder -> builder.path(EXCHANGE_RATE_API_PATH)
적용해 보겠습니다!

2023-08-13 13:44 UTC, bkRyusim commented on src/main/java/shopping/domain/order/OrderItem.java
> +    private Price price;
네 Price에 한해 분리하는 편이 좋을것 같습니다!

2023-08-13 14:12 UTC, bkRyusim commented
안녕하세요! 금요일 저녁부터 몸이 안 좋아서 리뷰가 조금 늦었습니다 ㅠㅠ
항상 리뷰 감사드립니다!

### 수정 사항
- 코드 106(API 요청 많은 경우), Timeout 시 retry 로직 추가
- API 키를 환경변수로 등록하도록 변경
- test용 application.properties 설정
- OrderItem의 Price와 Product의 Price 분리
- 외부 API를 호출하는 로직을 트랜잭션 이전에 호출하여 트랜잭션 자원 최소화

2023-08-15 12:23 UTC, begaonnuri approved these changes
안녕하세요 승윤님, 리뷰 잘 반영해주셨네요.
이번 미션은 여기서 머지하겠습니다. 리뷰 반영하시느냐 고생하셨습니다.

2023-08-15 12:23 UTC, begaonnuri commented on src/test/java/shopping/infrastructure/CurrencyLayerExchangeRateProviderTest.java
> +    @DisplayName("Timeout에 의해 실패하면 retry.")
꼭 이런 경우가 아니더라도 사용자가 와이파이 대신 LTE를 사용한다던가, 네트워크의 일시적인 오류로 언제든 발생할 수 있으니 retry, timeout과 같은 옵션을 잘 활용하시는게 좋습니다.

2023-08-15 12:24 UTC, merged