Step4, 5: 주문
next-step/spring-shopping-old pull request #24
Opened 2023-08-09 15:42 UTC by gunner6603

안녕하세요, 쇼핑 미션 4, 5단계 구현 완료했습니다!

- 여쭤보고 싶은 부분
  - 현재 `Order` 내부에 `OrderItem` 리스트를 `@OneToMany`를 사용해서 넣어 두었는데, 조회 시 사용하기는 편하지만 참조가 양방향으로 있어서 로직이 다소 복잡해지는 것 같습니다. (예를 들어 `OrderItem`을 생성할 때, 파라미터로 들어온 `Order` 객체에 `OrderItem`을 추가해줍니다.) 보통 이런 경우에는 단방향 참조와 양방향 참조 중 어느 것을 이용해야 하는지 궁금합니다!
  - `OrderService`의 `order` 메서드의 경우, 현재 `DB 호출 - 검증 - 외부 API 호출 - DB 호출`과 같은 로직으로 구성되어 있습니다. 외부 API 호출의 경우 시간이 오래 걸릴 수도 있기 때문에 트랜잭션에서 분리하고 싶다는 생각을 했는데요. 그런데 이를 위해 로직 순서를 `외부 API 호출 - DB 호출 - 검증 - DB 호출`로 변경하면 빈 장바구니와 같이 주문이 실패해야 하는 경우에도 매번 외부 API가 호출되는 문제가 발생합니다. 혹시 API 호출을 트랜잭션과 분리하는 좋은 방법이 있을까요?

2023-08-10 17:19 UTC, yjksw requested changes
안녕하세요 🙇‍♀️
구현해주신 코드 잘 확인했습니다 !! 

큰 변화 없이 추가기능을 잘 구현해주셨어요.
몇 가지 코멘트 남겼는데 확인 부탁드려요 ~!

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/config/ExchangeRateProviderConfig.java
> +    }
이것은 환율 provider 설정보다는 restTemplate 설정에 가까운 것 같은데요, 
만일 환율 조회 말고 다른 기능이 외부 api 호출이 있으면 이 설정을 공유하게 되나요 ? ㅎㅎ 

그러면 별도 config로 분리해도 좋을 것 같아요 !

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    @GeneratedValue
참고차 말씀드리면 키 생성전략은 주로 identity가 많이 사용됩니다. (제 경험에 한 해서요) 

sequence 전략을 선택하신 이유가 무엇인가요 ? identity와 sequence의 차이는 무엇이고 어떤 장단점이 있을까요 ?

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    @GeneratedValue
또한 기본값이더라도 명시적으로 작성해주는 것이 좋습니다. 
기본 설정이 언젠가 바뀔수도 있기 때문이에요

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/domain/vo/Money.java
> +public class Money {
저는 Money와 DollarMoney 클래스의 차이를 알기 어려운 것 같아요 ! 
Money는 다른 통화도 모두 포함하는 더 큰 범위의 클래스일까요 ? 
만약에 그렇다면 그런 부분이 코드에서 보여져야할 것 같아요. 아니라면 DollarMoney가 별도 클래스로 존재하지 않아도 되겠군요 ㅎㅎ

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    private List<OrderItem> orderItems = new ArrayList<>();
질문 주신 부분이군요 ! ㅎㅎ 
어떤게 더 좋다는 정답은 없고, 상황마다 다를 것 같은데요

말씀하신대로 양방향 참조가 필요하고 부가 메서드가 필요한 것도 사실이지만 그것이 무조건 지양해야하는 방법은 아닐 수 있어요.
만약에 이렇게 하지 않는다면 다른 어떤 방법에 대해서 생각해보셨나요 ?
다른 대안을 가지고 그것과 장단점을 비교해서 택일을 하면 좋을 것 같아요 ㅎㅎ

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/service/OrderService.java
> +        final ExchangeRate exchangeRate = exchangeRateProvider.fetchExchangeRate();
질문 주신 부분이군요 ㅎㅎ
저는 환율이 Order와 함께 묶이는 것이 좀 어색하게 생각되어요.
아예 별도의 기능이라고 생각하고 별도의 요청으로 환율은 따로 조회해서 화면에서 조합하는 방법으로 구현할 것 같네요 !

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/service/OrderService.java
> +            .forEach(orderItemRepository::save);
JPA에서 연관객체 영속화를 지원하는데 따로 저장하신 이유가 무엇인가요 ?

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/service/OrderService.java
> +        final User user = userRepository.getReferenceById(userId);
Order에 user가 있는데 또 따로 조회하시는 이유가 무엇인가요 ? 
또 조회할 필요 없이 입력으로 들어온 id와 비교하면 좋을 것 같아요 !

코드 흐름 상 의도를 파악하기 더 쉽지 않을까 싶네요

2023-08-10 17:19 UTC, yjksw commented on src/main/java/shopping/cart/utils/currency/ExchangeRateProvider.java
> +public interface ExchangeRateProvider {
요것이 과연 util 클래스에 있는 것이 마땅할까요 ? 
util은 정말 domain과 아예 상관이 없는 유틸리티 성 클래스의 집합이어야 합니다. 
예를 들어서, 정수 두 개를 받아서 더한 값을 반환하는 등의 기능들이 유틸리티라고 할 수 있어요. 

하지만 이 부분은 굉장히 도메인 핏하고 애플리케이션 주요 기능에 가깝다고 생각이 되네요 !

2023-08-10 17:19 UTC, yjksw commented on src/test/java/shopping/cart/service/OrderServiceTest.java
> +class OrderServiceTest {
모킹하다보니 서비스에서 유의미한 테스트가 많지 않고 통합테스트로 많이 작성하신 것 같아요 ㅎㅎ 
근데 그러면 세부적인 데이터가 의도대로 반환되고 있는지 확인하기 어려운 부분도 있습니다. 
서비스 단위테스트가 진행되었다면 JPA 테스트를 필수로 하면 좋을 것 같아요. 여기서 진행하지 못한 데이터 조회 테스트를 상세하게 할 수 있기 때문이에요.

2023-08-11 01:12 UTC, gunner6603 commented on src/main/java/shopping/cart/config/ExchangeRateProviderConfig.java
> +    }
넵 별도 설정으로 분리해 보겠습니다!

2023-08-11 07:08 UTC, gunner6603 commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    @GeneratedValue
identity 전략을 사용하면 영속화를 진행할 때 pk를 가져오기 위해 insert 쿼리를 바로 전송하므로 쓰기 지연을 사용하지 못하는 문제가 발생한다고 알고 있습니다. 그래서 sequence 전략을 사용했는데요. 피드백을 받고 더 알아보니 sequence 전략을 사용하는 경우, 서버가 다운되었을 때 받아온 sequence 값들이 사라져서 값 사이에 공백이 생기는 문제가 발생하고, 무엇보다 다중 서버 환경에서는 pk 순서가 엔티티 생성순서와 일치하지 않을 가능성이 생기게 되는 것 같습니다. 엔티티 생성 순서가 pk 순서와 무조건 일치해야 하는 건 아니지만 이걸 일치시켜 놓으면 나중에 생성 순으로 정렬 시 pk에 걸려 있는 인덱스를 활용할 여지가 생기겠다는 생각이 들어서 identity 전략으로 바꾸기로 했습니다!

2023-08-11 07:10 UTC, gunner6603 commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    @GeneratedValue
넵 알겠습니다!

2023-08-11 07:26 UTC, gunner6603 commented on src/main/java/shopping/cart/domain/vo/Money.java
> +public class Money {
이 부분은 코드 작성하면서 고민했던 부분인데요! 현재 코드가 완성되기 전에는 MoneyType이라는 enum 클래스를 작성하고 Money 내부에 MoneyType 필드를 둬서 원, 달러 모두 Money로 나타냈습니다. 그런데 그렇게 하니까 DB에도 MoneyType을 저장할 필요성이 생기게 되고, MoneyType에 대한 의존성이 여기저기(ExchangeRate, ExchangeRateProvider 등) 퍼지고, 확장에 지나치게 열리게 되어 애플리케이션이 복잡해진다는 느낌을 받았습니다. 그래서 변환 대상을 달러로 한정지었고, Money와 MoneyType으로 통화를 나타내기 보다는KRW를 나타내는 Money와 USD를 나타내는 DollarMoney만 사용하자는 결론에 도달했습니다. 현재 Money 클래스명을 WonMoney로 변경하기는 했는데 추가적인 변경이 필요할까요?
현재 WonMoney는 내부 타입으로 long을 가지고, DollarMoney의 경우 소수점도 중요하기 때문에 double 필드를 가지고 있는 등 내부 필드 차원에서의 차이는 가지고 있습니다!

2023-08-11 08:09 UTC, gunner6603 commented on src/main/java/shopping/cart/service/OrderService.java
> +            .forEach(orderItemRepository::save);
cascade를 설정해 둔 것을 깜빡했습니다! order만 영속화하도록 변경하겠습니다!

2023-08-11 08:09 UTC, gunner6603 commented on src/main/java/shopping/cart/service/OrderService.java
> +        final User user = userRepository.getReferenceById(userId);
넵 이 부분도 변경 진행하겠습니다!

2023-08-11 08:18 UTC, gunner6603 commented on src/main/java/shopping/cart/domain/entity/Order.java
> +    private List<OrderItem> orderItems = new ArrayList<>();
단방향 참조로 바꾼다면 주문 생성과 조회 시에 Order와 OrderItem 객체들을 따로 저장하고, 따로 불러오려고 했습니다! 이런 부분이 번거로울 것 같아서 고민이 되었던 건데요. 아래 피드백에서 cascade 관한 내용을 짚어 주셔서 이를 적용해 보았습니다! Order 팩토리 메서드에서 cartItem 리스트를 받아서 Order 객체를 생성하고 이를 한 번만 영속화하는 방식으로 코드를 변경해 보았는데 Order에 CartItem 종속성이 생겼지만 더 응집도 높은 코드가 된 것 같습니다.

2023-08-11 08:44 UTC, gunner6603 commented on src/main/java/shopping/cart/utils/currency/ExchangeRateProvider.java
> +public interface ExchangeRateProvider {
일단 환율을 가져오는 부분이 서비스 로직과 밀접하게 연관되어 있다고 생각해서 service 패키지로 옮겨두었는데 더 좋은 방법이 있을까요? 아직 어떤 기준으로 패키지를 설정해야 하는지 잘 모르겠습니다..

2023-08-11 09:19 UTC, gunner6603 commented on src/main/java/shopping/cart/service/OrderService.java
> +        final ExchangeRate exchangeRate = exchangeRateProvider.fetchExchangeRate();
그런데 주문 당시의 환율을 주문 상세조회 시마다 보여줘야 해서 주문과 함께 환율을 저장해야 할 것 같습니다. 주문과 환율 데이터를 동시에 저장하되 조회는 따로 하려면 주문 pk를 외래키로 가지는 환율 테이블을 생성해야 하는데 혹시 이렇게 구현하는 방법을 말씀하시는 건가요?

2023-08-11 09:23 UTC, gunner6603 commented on src/test/java/shopping/cart/service/OrderServiceTest.java
> +class OrderServiceTest {
넵 그런데 혹시 JPA 테스트가 DB 연동 테스트를 말씀하시는 건지 아니면 기존처럼 리포지토리를 모킹하는 서비스 단위 테스트를 만들되 서비스 계층 리턴값에 데이터가 잘 들어가 있는지 확인하라는 말씀이신지 잘 모르겠습니다. 어떤 걸 의미하시는 건가요?

2023-08-14 09:22 UTC, yjksw commented on src/main/java/shopping/cart/domain/vo/Money.java
> +public class Money {
그랬군요 !! 
처음에 enum을 추가했다가 변경하신 이유 (의존성)에 대해서 잘 생각해주셨어요.
실제로 enum을 지양하기도 하는 경우에는 static처럼 여기저기 의존성이 생기기 때문인 경우도 있답니다. 

지금 WonMoney로 수정해주셨으면 충분한 것 같아요 👍

2023-08-14 09:26 UTC, yjksw commented on src/main/java/shopping/cart/service/OrderService.java
> +        final ExchangeRate exchangeRate = exchangeRateProvider.fetchExchangeRate();
아하 주문당시의 환율을 그때 보여줘야한다는 부분을 제가 간과했네요 ! 
기존 질문으로 돌아가서 트랜잭션 분리를 하는 방식으로는 
1. 트랜잭션 전파 속성 변경 
2. 비동기 API 호출 
 
위 두 가지 방법을 많이 쓰곤 합니다. 아니면 여전히 구조적으로 풀 수 있는 방법이 있는지도 고민해봐도 좋을 것 같아요 ~

2023-08-14 09:29 UTC, yjksw commented on src/main/java/shopping/cart/utils/currency/ExchangeRateProvider.java
> +public interface ExchangeRateProvider {
패키지를 분리하는 명확한 규칙이 있지는 않은데요, 
저 같은 경우는 우선 통용되는 개념에서 크게 벗어나지 않게 패키지 책임을 지정하려고 합니다. (위 util과 같은 경우도 여기에 포함되어요) 

패키지를 나눈다는 것은, 이 코드를 보는 개발자가 이 애플리케이션의 구조와 코드 구현 시 어디를 보아야 할 지 도와주는 (인지적 과부하 방지)의 역할을 하는 것이라고 생각하는데요

코드를 작성한 당사자가 아닌 다른 사람이 본다면 특정 기능을 어느 패키지에서 찾기 시작할까? 라는 질문을 던지면서 분리를 하려고하는 것 같아요. 

또한, 의존성이 단방향으로 흐르도록 고려하며 패키지를 설정합니다 😊

2023-08-14 09:32 UTC, yjksw commented on src/test/java/shopping/cart/service/OrderServiceTest.java
> +class OrderServiceTest {
DB와 관련된 테스트는 별도로 작성되어야하고, 서비스는 DB를 포함한 통합테스트 또는 서비스레이어(모킹) 테스트를 해야합니다. 
어떤 테스트가 더 필요할지는 애플리케이션 성격에 따라서 다를 것 같네요 !
여유가 된다면 서비스 등등에 대한 통합, 단위테스트를 모두 진행하는 것이 좋지만, 유의미한 테스트가 아니거나 리소스가 부족하면 선택을 해도 좋을 것 같아요.

2023-08-14 11:00 UTC, gunner6603 commented on src/main/java/shopping/cart/service/OrderService.java
> +        final ExchangeRate exchangeRate = exchangeRateProvider.fetchExchangeRate();
답변 감사합니다!

2023-08-15 06:48 UTC, gunner6603 commented on src/test/java/shopping/cart/service/OrderServiceTest.java
> +class OrderServiceTest {
넵 서비스 단위 테스트로는 값이 잘 저장되었는지, DB와 적절하게 상호작용하는지 확인하지 못하는 것 같아서 `CartService`와 `OrderService`에 대한 단위 테스트를 DB와 연결한 통합 테스트로 변경했습니다!

2023-08-15 06:50 UTC, gunner6603 commented on src/main/java/shopping/cart/utils/currency/ExchangeRateProvider.java
> +public interface ExchangeRateProvider {
답변 감사합니다!

2023-08-15 07:01 UTC, gunner6603 commented
피드백 주신 부분 적용해 보았습니다! 목록은 다음과 같습니다.

- `RestTemplate` 설정 분리
- 테이블 기본 키 생성 전략 변경
- 외부 API 호출 부분을 서비스에서 분리
- 외부 API로부터 얻은 환율 값을 캐싱하도록 변경 (1분마다 삭제)
- 외부 API 호출 모듈 `component` 패키지로 이동
- `CartService`와 `OrderService`에 대한 단위 테스트를 통합 테스트로 변경

외부 API를 통해 환율 정보를 가져오는 데 500~600ms 정도 걸려서 환율 정보를 가져오는 로직을 트랜잭션 내에서 실행하지 않고 밖으로 빼냈습니다. 어떤 방식으로 빼낼지도 고민해 보았는데요. 트랜잭션 매니저를 활용하거나 다른 서비스 객체를 만드는 방식을 사용하면 코드가 너무 복잡해지는 것 같아서 컨트롤러에서 `ExchangeRateProvider`를 호출해서 서비스로 환율 정보를 넘겨주는 방식을 택했습니다.

2023-08-15 15:54 UTC, yjksw approved these changes
안녕하세요 🙇‍♀️
리뷰 적용 해주신 것 확인 했습니다 ~! 

리뷰 하나하나 질문과 본인의 생각을 달아주셔서 코드에 대해서 더 잘 이해할 수 있었어요 👍
전반적으로 잘 구현해주셔서 머지하려고 합니다 ! 

마지막 미션까지 수고 많으셨습니다 😊
남은 교육도 화이팅 이에요 ~!

2023-08-15 15:54 UTC, yjksw commented on src/main/java/shopping/cart/controller/api/OrderController.java
> +        final OrderResponse orderResponse = orderService.order(userId, exchangeRateProvider.fetchExchangeRate());
여러가지를 시도해보면서 잘 변경해주셨어요 ~! 💯

이 부분에 대해서 고민해보았을 때, 저는 주문과 환율이 별도 기능이라는 생각이 들어요. 

첫 번째로, 컨트롤러에서 한 트래잭션에서 잡히지 않도록 잘 분리해주셨는데, 여전히 하나의 api 안에 외부 api를 찌르는 로직이 함께 있기 때문에 요청 timeout에 대한 문제가 존재할 수 있어야 할 것 같아요.
두 번째로, 환율을 구하는 외부 api에 장애가 있을 경우 현재 애플리케이션의 주문까지 불가하는 것이 알맞을까 고민이 되는 것 같아요. 환율이 보이지 않아도 주문은 가능해야 더 안정적인 서비스가 될 것 같아요 ㅎㅎ

현재 미션에서 구현하기는 다소 복잡할 수 있지만, 
우선 주문을 완료하여 반환하고, 화면에서 주문 성공 시 반환된 주문금액으로 환율정보를 재조회하여 기능을 분리하면 좋을 것 같아요 ! 
최초 1회에 환율을 조회하고, 한번 조회한 뒤에는 주문에 환율금액을 저장하여 이후에는 저장된 당시 환율금액을 조회하도록 설계해도 좋을 것 같네요.

참고차 말씀드립니다 😊

2023-08-15 15:54 UTC, yjksw commented on src/main/java/shopping/cart/domain/entity/Order.java
> +        if (totalPrice.compareTo(BigInteger.valueOf(MAX_TOTAL_PRICE)) > 0) {
꼭 수정이 필요한 부분은 아닙니다 ㅎㅎ
`compareTo` 는 가독성이 다소 떨어지는 단점이 있답니다.
가능하다면 부등호로 표현이 가능한 부분은 부등호로 표현을 하도록 구현하는 것도 좋은 방법이에요 ~!

2023-08-15 15:54 UTC, yjksw commented on src/main/java/shopping/cart/domain/entity/OrderItem.java
> +    private Quantity quantity;
컨벤션이 따로 있는 것은 아니지만, 
개인만의 컨벤션을 가지고 가독성 있게 개행을 해보아도 좋겠네요 !

2023-08-15 15:54 UTC, yjksw commented on src/test/java/shopping/cart/domain/entity/OrderTest.java
> +        final ShoppingException exception = assertThrows(ShoppingException.class,
이미 아실 수 있지만 참고차 말씀드립니다 ㅎㅎ
`assertThatThrownBy()` 라는 것도 있으니 비교해보고 더 적절한 것을 사용해도 좋겠네요

2023-08-15 15:54 UTC, yjksw commented on src/test/java/shopping/cart/service/CartServiceTest.java
> +        assertThat(firstCartItem.getQuantity()).isEqualTo(new Quantity(1));
`extracting` 이라는 키워드도 학습해보고 적용하면 더 심플한 테스트코드를 작성할 수 있을 것 같아요 🙌

2023-08-15 15:54 UTC, yjksw commented on src/test/java/shopping/cart/service/OrderServiceTest.java
> +        final OrderItem firstOrderItem = order.getOrderItems().get(0);
`usingRecursiveComparison` 이라는 키워드도 학습해보고 적용해보아도 유용할 것 같네요 ! ㅎㅎ

2023-08-15 15:54 UTC, merged