Step 4, 5: 주문, 주문 (환율 적용)
next-step/spring-shopping-old pull request #32
Opened 2023-08-11 12:07 UTC by whatasame

안녕하세요. 우아한테크캠프 6기 최정규입니다.

네 번째 미션 쇼핑의 4, 5단계 미션에 대한 Pull request입니다.

> 웹 페이지 이용을 위한 샘플 회원 정보는 다음과 같습니다.
 아이디: `woowacamp@naver.com`  비밀번호: `woowacamp`
 
> Currency layer API key를 환경 변수로 분리하였는데 필요 시 DM 주시면 알려드리겠습니다!

## 본인의 상황

JPA 공부를 병행하면서 미션을 진행했는데 잘 적용했는지 의문이 듭니다. 만약에 보시다가 의문이 들거나 잘못된 점 있으면 과감없이 지적 부탁드립니다!!

## 코드를 작성할 때 신경 쓴 점

* 외부 API 의존도 약화
  * 환율 API를 바꾸더라도 변경을 최소화할 수 있도록 설계
  * 환율 API에 문제가 발생하더라도 원화 주문은 가능하도록 설계
  * 실제 API에 의존하지 않고 테스트 통과하도록 설계  

## 구현 사항

* 4, 5단계 요구 사항
* CartProduct와 Product 사이의 연관 관계 설정
* HTML 테스트 강화

## 질문 

이전 코멘트에 대한 질문 사항입니다.

### [장바구니 물품과 물품 사이의 연관 관계](https://github.com/next-step/spring-shopping/pull/17#discussion_r1288356617)

> cart pacakage가 product 패키지를 참조하지 않나요? 패키지간 양방참조는 클래스와 마찬가지로 좋지 않은 패턴임은 맞지만, 이 경우엔 cart -> product로 참조를 일방향으로 제한할 수 있을것 같아 사이클이 생성될거란 부분에선 확실히 이해되지 않았습니다

JPA를 다룬 지 얼마 되지않아 양방향 관계만을 생각하고 있었습니다. 단방향으로 설계하면 의존성 사이클 문제가 발생하지 않네요. 😭

> 또한 CartProduct와 Product의 life cycle이 독립적인 객체가 맞을까요? 장바구니 상품이란 상품의 하위도메인 아닌가요? Product 생애주기에 CartProduct가 전적으로 의존하지 않나요?

제 머릿 속의 장바구니는 물품이 삭제됐을 때 이를 감지하고 장바구니에서 `삭제된 물품입니다` 등의 메시지를 출력한다고 생각했습니다. 따라서 장바구니 물품과 물품의 life cycle이 다르다고 생각했었는데요. 그러나 제가 정의한 요구 사항에는 이에 대한 것이 적혀있지 않아 life cycle이 동일하다고 판단하여 연관 관계를 맺도록 수정하겠습니다.

그런데 제가 생각한 것처럼 원본 물품이 삭제(혹은 판매 중지)될 때 장바구니 상품이 남아있고 사용자에게 정보를 줘야한다면 life cycle이 다르다고 생각하는데요. 이 경우에는 ID로 연관 관계를 맺는 것이 적절할까요?

### [indirection의 적절한 사용](https://github.com/next-step/spring-shopping/pull/17#discussion_r1288375609)

모든 문제을 indirection으로 해결할 수 있다는 말을 듣고 제 자신을 돌아봤던 것 같습니다. 한편으로는 하나의 룰(life cycle이 다르면 indirection)을 절대적으로 적용하려했던 것 같기도 합니다. 

그렇다면 의문이 드는 점이 어디까지를 객체 참조로 연관 관계를 맺고 어디에서 끊어서 ID로 연관 관계를 맺어야할까요? 이 역시 정답은 없을 것 같은데요. 제가 생각하기엔 비즈니스 로직을 풀어야하는 도메인 사이의 관계에 의해 결정할 것 같습니다. 리뷰어님은 어떤 기준을 가지고 계신 지 궁금합니다.

그 외 궁금한 점은 코멘트로 달겠습니다.

2023-08-11 12:20 UTC, whatasame commented on src/main/java/shopping/exception/OrderExceptionType.java
> +    private final String message;
* https://github.com/next-step/spring-shopping/pull/17#discussion_r1288429701

위 코멘트에서 말한 중복은 필드와 getter를 말한거였습니다!

`ExceptionType`을 구현하는 enum 클래스에서 공통적으로 `httpStatus`, `message`, `getHttpStatus()`, `getMessage()`를 정의해야하는데 더 좋은 방법이 있을까요?

2023-08-11 12:20 UTC, whatasame commented on src/main/java/shopping/dto/response/OrderDetailResponse.java
> +            null
DTO의 field가 null일 경우 null 값이라도 직렬화를 하는 것이 좋을까요? 아니면 직렬화 대상에서 제외하는 것이 좋을까요?

환율 API가 정상 동작하지 않더라도 주문은 할 수 있도록 설계하였는데요. `currencyRate`의 null 유무에 따라 javascript에서 처리를 하고 있습니다. 물론 환율을 구하는 API를 별도로 둬서 서로 다른 DTO를 사용하는게 좋겠지만 현재 상황에서 어떤 선택지가 좋을 지 궁금합니다.

2023-08-12 07:00 UTC, sihyung92 requested changes
안녕하세요 정규님~! 
JPA를 다룬지 얼마 안 되셨다고 했는데 잘 사용해주고 계시네요 ㅎ
몇가지 리뷰 남겼으니 확인해주셔요. 감사합니다~~

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/exception/OrderExceptionType.java
> +    private final String message;
이 경우엔 구현 자체를 편하게 하는 뾰족한 수는 없는거 같습니다 ^_^ ㅎㅎ;
enum이 아니라면 이런 불편을 해소하기 위해 abstract class 를 사용하겠지만 enum은 abstract class의 상속이 제한되어 있어서요

제가 다루는 프로덕션 코드에도 비슷한 경우가 있는데 롬복의 @Getter를 활용해 좀더 손쉽게 override하기는 합니다
그리고 롬복을 사용하지 않더라도 IDE가 편하게 만들어주니까.. 그정도 선에서 만족해야하지 않을까 싶네요

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/repository/OrderRepository.java
> +    Optional<Order> findByIdAndMemberIdWithOrderProduct(final Long orderId, final Long memberId);
다른 리뷰이 코드를 보다 말로만 듣던 @EntityGraph를 적용해주신 걸 보았는데요, 간단한 패치조인의 경우 패치 조인을 추상화한 어노테이션인 EntityGraph를 활용해주는 방법도 있을거 같습니다 ㅎ
```suggestion
    @EntityGraph(attributePaths = {"orderProducts"})
    Optional<Order> findByIdAndMemberId(final Long orderId, final Long memberId);
```

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/controller/CartProductController.java
> +        return ResponseEntity.ok().body(cartProductService.createCartProduct(memberId, request));
성공 응답에 생성 데이터 내려주시는 부분 좋습니다 👍
다른 패턴으로는 201 (Created)를 내려주고 location 헤더에 해당 자원을 요청할 수 있는 path를 전달해주는 패턴도 있습니다
( "location": "/api/cartProduct/1" )

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/controller/CartProductController.java
>      @PostMapping
변경하신 부분이 리뷰가 되지 않아 여기에.. ㅎㅎ

api 설계를 카멜케이스로 해주셨던데 보통 케밥케이스 ( "api/cart-product" ) 식으로 많이 하는 것 같습니다.
관례로 쓰던거라 이유는 잘 모르겠지만 URL의 역사가 길다보니 ignoreCase하는 서버가 많았으려나? 인코딩 문제였으려나? 대략 생각만 해봅니다 ㅎ

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/controller/CartProductController.java
>      @PostMapping
리뷰 남기고 간단하게 구글링 해봤는데 정하기 나름인거 같네요 ㅎ

IBM Rest API 규칙에선 [카멜케이스](https://www.ibm.com/docs/ko/urbancode-build/6.1.2?topic=reference-rest-api-conventions)를, 
[박가람님(블로그 필자)](https://www.rocketpunch.com/cards/post/436146)은 케밥 케이스를 쓰자고 주장하고 있네요.

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/domain/order/OrderProduct.java
> +    // TODO: 양방향 필요?
한국에선 JPA 바이블로 통하는 영한님은 가급적 ManyToOne 단방향만 사용할 것을 권하시긴 하셨지만 이런 경우처럼 Order에서 OrderProducts를 탐색하는게 더 자연스러워 보일 때도 있는데요, 

필요한 경우 이번 경우처럼 양방 맵핑에서 발생할 수 있는 가능성만 조심해서 (mappedBy 설정 등) 써주면 문제없다고 생각해요~

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/service/OrderService.java
> +        cartProductRepository.deleteAllByMemberId(memberId);
비즈니스 플로우 상 좀더 맥락있는 메서드명을 써주거나 주석을 작성해주면 좋을꺼같아요 ㅎ 어떤 의도로 cartProduct를 지우는지 잘 드러나게요

```suggestion
       cleanUpCart(memberId);
```

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/service/OrderService.java
> +            .orElse(OrderDetailResponse.from(order));
Read 트랜잭션도 길어지는 건 부담스럽기 때문에 API 조회부는 트랜잭션과 분리해주는게 좋습니다. 트랜잭션과 API 호출부 분리를 위해 객체 분리가 더 필요해지는 시점이네요.

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
질문에 대한 답변입니다~!

> 그런데 제가 생각한 것처럼 원본 물품이 삭제(혹은 판매 중지)될 때 장바구니 상품이 남아있고 사용자에게 정보를 줘야한다면 life cycle이 다르다고 생각하는데요. 이 경우에는 ID로 연관 관계를 맺는 것이 적절할까요?

"장바구니"와 "장바구니 물품"은 다르지 않나요? 
장바구니의 생명주기는 유저에 의존적이고, (유저 생명주기 내부에 포함됨)
장바구니 물품의 생명주기는 유저 및 상품 모두에 의존적이라고 생각합니다 (유저 생명주기 & 상품 생명주기 둘 내부에 모두 포함됨)

장바구니에 대한 이해가 다를 수도 있겠네요 ㅎ 전 상품이 삭제되면 장바구니에서도 밀려야된다고 생각합니다. 
정규님은 반대로 장바구니 상에서 빗금 같은거라도 치면서 "삭제된 상품입니다" 라고 노출되어야 한다고 생각하시는 거죠?

(이하 답변은 또 다른 질문에 대해서 답변도 되겠네요 > _ID로 분리하는 기준은 어디까지.._ )

제가 ID 분리할 때 기준은 유즈케이스입니다. 제가 product 에 대해서는 참조 리뷰를 드리고 memberId는 아무 리뷰도 하지 않은 이유는, 실제 장바구니 조회패턴에서 상품정보는 필수적이고 멤버정보는 그렇지 않기 때문입니다. 필수적인 정보는 항상 함께 가지고 오게, 그렇지 않은 멤버정보는 적당히 간접참조 해두어도 괜찮다고 봐서요 (member를 직접 참조해도 상관없다고 생각합니다. join 부담이 작을거 같아서요)

만약 장바구니에서 빗금을 쳐서 삭제상품을 표시해준다는 요구사항이라고 하더라도, 저는 Product를 ID참조로는 바꾸지 않을것입니다. 왜냐하면 ID 참조 (간접참조, 최소정보)에선 상품이 삭제되었다는 정보를 알 수 없기 때문입니다. 
이를 위해 항상 상품에서 ID를 통한 조회를 해서 merge 방식으로 내려주는 게 항상 강제될텐데, 이 방식은 현재처럼 객체참조를 그대로 가지고 있는 것보다 개발을 복잡하게 만듭니다. 

저도 2년전 즈음 이번 미션에 주요 화두로 잡으신 조영호님의 객체지향 세미나 영상을 매우 감명깊게 보았던 기억이 있는데요, 저도 간접참조 방식에서 충격을 느끼긴 했습니다만은, 제가 느낀 점은 **가급적 직접 참조를 하고** 거기에서 불필요한 코드가 강요되면 **필요에 의해서 간접 참조로 분리를 하자** 였습니다.

2년이 흐른 지금도 마찬가지로 생각하는데요, 전 우선 최대한 단순하고 쉬운 방식(여기에선 직접 참조)으로 구현을 하고 거기서 파생하는 문제점들을 수정하기 위해 리팩토링을 하는 것이 더 좋다고 생각합니다. ( 어떤 내용을 수강하시는지 정확히 모르지만 우아한테크캠프에서도 비슷한 내용을 전달할거라 생각합니다. `돌아가는 쓰레기가 돌아가지 않는 클린코드 보다 낫다` 는 격언이 이와도 연결된다고 봐요 )

2023-08-12 07:00 UTC, sihyung92 commented on src/test/java/shopping/fake/FakeCurrencyExchanger.java
> +public class FakeCurrencyExchanger implements CurrencyExchanger {
조금더 간단하게 아래처럼 해두면 TestConfig 객체가 필요 없습니당!
```suggestion
@Primary
@Component
public class FakeCurrencyExchanger implements CurrencyExchanger {
```

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/exchange/CurrencyLayerCurrencyExchanger.java
> +public class CurrencyLayerCurrencyExchanger implements CurrencyExchanger {
패키지 밖에서 알아야 하는 CurrencyExchanger, CurrencyType 외엔 default 접근제어자 여도 될 거 같아요.

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/exchange/CurrencyLayerClient.java
> +public class CurrencyLayerClient {
패키지 밖에서 알아야 하는 CurrencyExchanger, CurrencyLayerCurrencyExchanger, CurrencyType 외엔 default 접근제어자 여도 될 거 같아요.

2023-08-12 07:00 UTC, sihyung92 commented on src/test/java/shopping/exchange/CurrencyLayerClientTest.java
> +    void sendLiveCurrencyExchangeRateRequest() {
외부 의존성을 위해 Currency Server를 mocking하는 설정을 넣는건 좋지만, 
실제 API를 호출하는 테스트를 만들고 @Disabled를 붙여서 필요할 때만 켜볼 수 있게 해두면 좋을거 같아요. 실제 요청 응답값이 궁금한 개발자들이 더 많을거라서요

2023-08-12 07:00 UTC, sihyung92 commented on src/main/resources/application.yml
> +  access-key: ${CURRENCY_LAYER_ACCESS_KEY}
감추어야할 API key를 어떤 방식으로 감추는지 DM으로 여쭤보았는데,

환경 변수로 주입하는 방식 / 잠시 application.yml을 수정하는 방식을 이야기해주셨습니다.

1. 환경 변수로 주입하는 방식 
  - 지금은 감추어야할 키가 하나지만, 실제로는 수십가지에 이르는 경우가 많아서요. 이럴 땐 일일이 환경변수로 주입하기가 어려워질거 같아요 ㅎ 이럴 땐 파일로 만들어두고 export 명령어를 이용해 집어넣는 경우가 있습니다.

2. yml로 주입하는 방식
  - 이럴 땐 아예 별도 yml파일로 분리하는 게 낫습니다. application-cryption.yml (막지어봤습니다)를 만들고, yml 파일을 손에서 손으로 전달하고, git ignore 처리를 해두는 방법입니다. 이런 방식을 사용하면 README.md 등에 어떻게 yml 파일을 얻을 수 있는지 명시해두는게 좋습니다
  - 전 git submodule (다른 레포지토리 코드를 포함하는 방법)을 이용해 private repository로부터 받아오는 방식도 써보았는데, 러닝커브와 서브모듈 자체의 불편함(젠킨스랑 호환하기 힘들었음)이 좀 있었습니다 

방법은 많겠지만 저두 위 두 개 방법 정도가 생각나네유 ㅎㅎ 그냥 레포지토리를 private로 만들어두고 당당하게 넣는 것도 방법이고요 (저는 회사 코드를 짜니까.. 레포 자체가 private라서 이런 고민 없이 편하게 박아넣고 있습니다)

2023-08-12 07:00 UTC, sihyung92 commented on src/main/java/shopping/dto/response/OrderDetailResponse.java
> +            null
음 null이 진짜로 해당 필드가 없어서 null인지, 그 밖의 사유로 null인지에 따라 조금은 다를거 같아요.
진짜 null이면 반드시 포함을 해줍니다 (없다는 것도 정보니까요)
가짜 null이면 고민을 해볼 순 있는데, 그래서 클라이언트의 파싱 오류를 막기 위해 가급적 내려주기는 하는거 같아요.

2023-08-13 05:19 UTC, whatasame commented on src/main/java/shopping/dto/response/OrderDetailResponse.java
> +            null
결국 프론트엔드나 팀 내에서 합의가 필요하겠네요!

2023-08-13 05:21 UTC, whatasame commented on src/main/java/shopping/controller/CartProductController.java
> +        return ResponseEntity.ok().body(cartProductService.createCartProduct(memberId, request));
장바구니 상품을 딱 하나 조회하는 요구사항이 없어서 `Location` 헤더말고 생성 정보를 넘겨주도록 설계하였습니다.

2023-08-13 05:23 UTC, whatasame commented on src/main/java/shopping/controller/CartProductController.java
>      @PostMapping
두 글 모두 잘 읽었습니다! 케밥 스타일이 더 마음에 들어서 반영하도록 하겠습니다!

2023-08-13 05:56 UTC, whatasame commented on src/main/resources/application.yml
> +  access-key: ${CURRENCY_LAYER_ACCESS_KEY}
환경 변수를 별도의 파일로 관리하는 방법이 가장 마음에 드네요!! 적용해보겠습니다!

2023-08-13 13:10 UTC, whatasame commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
>  전 우선 최대한 단순하고 쉬운 방식(여기에선 직접 참조)으로 구현을 하고 거기서 파생하는 문제점들을 수정하기 위해 리팩토링을 하는 것이 더 좋다고 생각합니다. 

요즘 뭔가 이런 말을 자주 보거나 듣는 것 같은데 정말 공감합니다 ㅠㅠ 너무 먼 산을 보는 것 같네요.

---

아래는 말씀해주신 내용에 대한 질문입니다.

> 이를 위해 항상 상품에서 ID를 통한 조회를 해서 merge 방식으로 내려주는 게 항상 강제될텐데, 이 방식은 현재처럼 객체참조를 그대로 가지고 있는 것보다 개발을 복잡하게 만듭니다.

`merge 방식`이라는 것이 장바구니 정보를 조회하기 위해 `CartProduct`들을 불러오고, `CartProduct`에서 `Product` id를 뽑아 또 다시 Product를 가져온 후 조회 결과를 가공하는 과정으로 이해했는데 맞을까요?

> 제가 느낀 점은 가급적 직접 참조를 하고 거기에서 불필요한 코드가 강요되면 필요에 의해서 간접 참조로 분리를 하자 였습니다.

간접 참조를 쓰지 않아 직접 참조에서 불필요한 코드가 발생하는 경우가 있나요? 

간접 참조의 경우 이전 질문에서 제가 이해한 merge 방식과 같은 코드가 발생할 것 같은데 직접 참조의 경우는 잘 떠오르지가 않습니다.

---

아래는 별도로 궁금한 내용입니다.

> `CartProduct`와 `Product` 사이의 연관 관계를 객체 참조로 맺는 경우 의도치 않은 수정이 발생할 수 있다. 예를 들어 `Product`에서 상품 가격을 수정하는 메서드가 존재할 경우 `CartProduct`에서 언제든지 객체 참조로 해당 메서드를 호출 할 수 있다. 만약 연관 관계를 id로 맺는다면  `CartProduct`에서 `Product`의 메서드를 모르므로 이를 예방할 수 있다. 

직접 참조와 간접 참조에 대해서 고민하다 위 같은 생각이 떠올랐습니다. 이에 대해선 어떻게 생각하시는 지 궁금합니다.

2023-08-13 13:19 UTC, whatasame commented
안녕하세요~ 피드백 감사합니다!! 말씀해주신 내용을 학습하다보니 또 모르는 것들이 나와서 공부하느라 반영이 너무 늦었습니다 😭

말씀해주신 내용 중 일부는 반영하고 일부는 질문을 다시 남겼으니 확인 부탁드립니다.

항상 감사드립니다!

## 주요 변경점

* API endpoint URL을 카멜 케이스에서 케밥 케이스로 변경
* 실제 API 응답을 확인할 수 있는 테스트 추가
* API 관련 component를 `@Component`가 아닌 Configuration class에서 관리하도록 변경
* `@EntityGraph` 적용
* API 요청 로직을 Transaction에서 분리 

## 추가 질문

* https://github.com/next-step/spring-shopping/pull/32#discussion_r1292118406
* https://github.com/next-step/spring-shopping/pull/32#discussion_r1292118513

위 두 코멘트에서 언급한 접근 제어자가 어떤 것을 말씀한 것인지 이해하지 못했습니다. method의 접근 제어자를 말씀하신걸까요?

## 답변을 기다리는 코멘트

* https://github.com/next-step/spring-shopping/pull/32#discussion_r1292786617

2023-08-13 13:43 UTC, whatasame commented on src/main/java/shopping/config/AuthConfig.java
> +    public AuthConfig(final JwtInterceptor jwtInterceptor,
WebConfig에서 인증 관련 component와 HTTP 요청 관련 component를 둘 다 관리하고 있어 책임을 분리했습니다.

2023-08-13 13:43 UTC, whatasame commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
`Client`와 `Parser`를 Bean으로 등록하는 것이 맞을까요?

`Exchanger`는 확실히 Bean으로 등록하는 것이 맞다고 생각하는데 `Client`와 `Parser`는 `Exchanger`의 종류에 따라 있을 수도 있고 없을 수도 있다고 생각합니다. 또 이렇게 할 경우 `Exchanger`에 이상한 `Client`나 `Parser` 객체가 주입되어 예상하지 못한 결과가 나올 수 있다고 생각합니다. (예를 들어 `DummyCurrencyExchangeClient`가 있을 때 Configuration class를 잘못 수정하면 `CurrencyLayerExchanger`에 `CurrencyLayerCurrencyExchangeClient`가 아닌 `DummyCurrencyExchangeClient`가 실수로 주입될 수 있음)

질문을 작성하다보니 하나 아이디어가 생각났는데요.  `Exchagner`만 Configuration class에서 등록하고 `Client`와 `Parser`는 Interface 없이 단독 Class로서 `@Component`로 Bean 등록 후 Configuration에서 이들을 주입받으면 될 것 같네요.

2023-08-13 13:43 UTC, whatasame commented on src/test/java/shopping/exchange/CurrencyLayerCurrencyExchangerTest.java
> +    RestConfig.class})
최소한의 Bean을 이용하여 테스트를 할 수 있는 팁이 있을까요?

`@SpringBootTest`로 하는 테스트의 시간을 단축시키기 위해 이것저것 알아봤는데 매번 Bean이 없다고 예외가 터져서 많은 시간을 썼습니다 ㅠㅠ. Spring 테스트 시간을 줄일 수 있는 **방법을 잘 찾는 방법**이 궁금합니다

2023-08-14 13:13 UTC, sihyung92 requested changes
안녕하세요 정규님! 
리뷰 반영 잘 해주신 부분 확인하였고, 주로 코멘트 위주의 리뷰를 했으니 확인해주셔용.
DM에서 말씀주셨던 대로 기능 추가해주시고 다시 요청해주셔요 ㅎㅎ
감사합니다!

2023-08-14 13:13 UTC, sihyung92 commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
> 질문을 작성하다보니 하나 아이디어가 생각났는데요. Exchagner만 Configuration class에서 등록하고 Client와 Parser는 Interface 없이 단독 Class로서 @Component로 Bean 등록 후 Configuration에서 이들을 주입받으면 될 것 같네요.

아이디어 대안으로 제시해주신 방법은 어떻게 구성하실지 사알짝 이해가 안 갔습니다 ^_^ ㅎㅎ

대신 질문 자체에 대한 답변을 해보자면..

저는 빈 등록을 해야한다 / 말아야한다 에 큰 의미를 두진 않습니다. Bean이라는건 스프링 프레임워크에서 `DI를 쉽게 해줄 수 있는 대상`으로 다루겠다는 의미가 있으니까요, 일종의 편의기능이라고 보는 시각입니다.

그러면 빈 등록 대상을 판단하는 기준은 DI가 필요할지 아닐지를 따져보면 될텐데요, 의존성 주입이 필요한 경우는 보통 IoC (inversion of control == 인터페이스화)를 수행해서 인터페이스를 받아쓰는 객체 입장에서 (여기선  Exchagner가 되겠죠) 코드 수정 없이 다른 구현체를 갈아끼고 싶을 때일거에요.

그런데 말씀해주신 것처럼 Exchanger가 다른 구현체가 주입될 경우 오동작할 가능성이 있다면, 그래도 인터페이스는 유지해서 미래로부터의 변경사항으로부터 Exchanger를 보호하고 싶다면, Bean 등록을 통한 스프링의 도움을 받지말고 수동 DI (Dependency Injection, 의존성 주입) 해주면 됩니다. 방법은 생성자에다가 원하는 구현체를 직접 전달하면 될거구요.

(적다보니 서두에 이해가 안간다고 한 구성이 이걸 말씀하신거 같네요?)

```java
    @Bean
    public CurrencyExchanger currencyExchanger() {
        return new CurrencyLayerCurrencyExchanger(
            new CurrencyLayerCurrencyExchangeClient(baseUrl, accessKey, restTemplateBuilder),
            new CurrencyLayerCurrencyExchangeParser(objectMapper)
        );
    }
```

2023-08-14 13:13 UTC, sihyung92 commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
질문을 받은김에 보다보니 사실 config 객체 자체가 필요없지 싶기도 해요 ㅎㅎ
Component도 아시겠지만 빈 등록인데요, Bean이란 어노테이션이 별도로 존재하는 이유는 내가 빈등록 해야하는 객체를 직접 수정하지 못하는 상황에서 쓰기 위해서 입니다 (예컨데 외부 라이브러리 코드를 빈으로 만들어야하는 경우 처럼요 -> ObjectMapper 클래스의 코드를 제가 수정할 수 없으니까요. 참고로 ObjectMapper는 스프링부트가 미리 빈 등록을 해둔 경우입니다)

그래서 이 config 자체를 걷어내고 CurrencyLayerCurrencyExchangeClient 클래스 등 위에 @Component를 다는 식으로 수정하는 것도 괜찮을거 같습니다 ㅎㅎ 의존성을 주입받는 부분 외에 특별히 빈등록 설정을 따로 빼야하는 커스텀 설정은 보이지 않아서요

2023-08-14 13:13 UTC, sihyung92 commented on src/main/java/shopping/config/RestConfig.java
> +            .setReadTimeout(Duration.ofSeconds(1));
1초의 기준이 있을까요? 리드 타임아웃 1초는 조오금 빡빡할수도 있습니다 ㅎㅎ 
(특히나 공공기관 API 같은거 쓸때는요)

2023-08-14 13:13 UTC, sihyung92 commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
> 거기에서 불필요한 코드가 강요

요 부분은 제가 잘못 표현한 부분입니다 ㅎㅎ 불필요한 코드 보다는 "불필요한 상황"으로 정정할게용
예컨데 직접 참조를 해두면 항상 조인 쿼리가 나가게 되는데, 불필요한 조인으로 DB 부하가 커지고 있는 상황이라던지,
MSA로 분리 결정을 해서 모듈을 분리해야하는데, 코드가 직접참조하고 있어 리팩토링하기가 난감한 경우라던지 

이런 상황들을 의도하였습니다.

2023-08-14 13:13 UTC, sihyung92 commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
> CartProduct와 Product 사이의 연관 관계를 객체 참조로 맺는 경우 의도치 않은 수정이 발생할 수 있다...

요 부분은 선현(?)들이 방법을 마련해주셨습니다. 사실 개발에서 저희가 인류 최초로 맞닥뜨린 문제는 잘 없는 경우가 많은데 (고민이 거기서 거기라서요) 그럴 땐 라이브러리나 구글링 좀 해보면 보통 방법이 있는 경우가 많습니다.

사실 메모리 (= 스프링 어플리케이션) 상에서 객체가 수정되는 건 의도한 행위일테고, 걱정하시는 부분은 DB값이 맘대로 바뀌는 부분을 걱정하시는 걸거에요. @JoinColumn 보시면 updatable, insertable 칼럼이 있는데 false로 두면 그런 상황을 방지할 수 있습니다.

2023-08-14 13:13 UTC, sihyung92 commented on src/test/java/shopping/exchange/CurrencyLayerCurrencyExchangerTest.java
> +    RestConfig.class})
ㅎㅎ 넵 뾰족한 수는 없이.. 그나마 스프링이 예외를 친절하게 띄워주는 편이니 그때그때 주입을 못 받는 객체를 체크해 테스트 Import용 클래스를 따로 만들고 테스트에선 extends 해주는 게 최선이라고 생각합니다.

https://www.youtube.com/watch?v=N06UeRrWFdY 이거 예전에 같이 공부하던 친구가 SpringBootTest 시간을 단축하기 위해 삽질했던 경험을 담은 영상인데, 도움이 될거같아 첨부합니다

2023-08-15 05:28 UTC, whatasame commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
> (적다보니 서두에 이해가 안간다고 한 구성이 이걸 말씀하신거 같네요?)

제가 말을 이상하게 했는데 정확히 이해해주셨네요. 저도 `빈 등록 대상으로 판단하는 기준은 DI 필요 여부다.`라는 생각을 갖고 이야기한 것 같아요.

> 그래서 이 config 자체를 걷어내고 CurrencyLayerCurrencyExchangeClient 클래스 등 위에 https://github.com/component를 다는 식으로 수정하는 것도 괜찮을거 같습니다 ㅎㅎ 의존성을 주입받는 부분 외에 특별히 빈등록 설정을 따로 빼야하는 커스텀 설정은 보이지 않아서요

하나의 주제에 관련되어있지만 퍼져있는 Bean들을 한 곳에서 알 수 있게 Configuration에서 등록하는건 어떻게 생각하시나요?

한편으로는 package로 할 수 있는 일을 잘못된 package 분리로 인해 Configuration로 해결하는 느낌이 들기도 하네요.

2023-08-20 13:19 UTC, whatasame commented on src/test/java/shopping/exchange/CurrencyLayerCurrencyExchangerTest.java
> +    RestConfig.class})
영상 중간에 웨지? 하면서 시형님이 등장하는게 재밌네요..🤣

2023-08-20 13:21 UTC, whatasame commented on src/main/java/shopping/config/RestConfig.java
> +            .setReadTimeout(Duration.ofSeconds(1));
강의 시간에 1초가 적당할 것 같다고 이야기 해주셔서 적용해봤습니다. 

저도 Notion API를 사용했을 때 2초로 설정했다가 계속 time out이 떠서 5초로 늘린 적이 있었는데요. 

저처럼 테스트하며 늘리시는지 아니면 다른 기준이 있는지 리뷰어님의 생각이 궁금합니다!

2023-09-01 11:22 UTC, whatasame reviewed
안녕하세요. 너무 늦어서 죄송합니다.

누락한 기능 구현 및 궁금한 점 코멘트로 달았습니다!

2023-09-01 11:22 UTC, whatasame commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
> 예컨데 직접 참조를 해두면 항상 조인 쿼리가 나가게 되는데, 불필요한 조인으로 DB 부하가 커지고 있는 상황이라던지,
MSA로 분리 결정을 해서 모듈을 분리해야하는데, 코드가 직접참조하고 있어 리팩토링하기가 난감한 경우라던지

아하! 이해 했습니다.

> 사실 개발에서 저희가 인류 최초로 맞닥뜨린 문제는 잘 없는 경우가 많은데

해주시는 말 한마디 한마디가 너무 재밌네요ㅋㅋㅋㅋ 감사합니다!!! 고민이 드는게 있으면 항상 검색해봐야겠어요.

2023-09-01 11:22 UTC, whatasame commented on src/main/java/shopping/config/RestConfig.java
> +            .setReadTimeout(Duration.ofSeconds(1));
강의 시간에 1초가 적당할 것 같다고 이야기 해주셔서 적용해봤습니다. 

저도 Notion API를 사용했을 때 2초로 설정했다가 계속 time out이 떠서 5초로 늘린 적이 있었는데요. 

저처럼 테스트하며 늘리시는지 아니면 다른 기준이 있는지 리뷰어님의 생각이 궁금합니다!

2023-09-01 11:22 UTC, whatasame commented on src/test/java/shopping/exchange/CurrencyLayerCurrencyExchangerTest.java
> +    RestConfig.class})
영상 중간에 웨지? 하면서 시형님이 등장하는게 재밌네요..🤣

2023-09-01 11:22 UTC, whatasame commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
> (적다보니 서두에 이해가 안간다고 한 구성이 이걸 말씀하신거 같네요?)

제가 말을 이상하게 했는데 정확히 이해해주셨네요. 저도 `빈 등록 대상으로 판단하는 기준은 DI 필요 여부다.`라는 생각을 갖고 이야기한 것 같아요.

> 그래서 이 config 자체를 걷어내고 CurrencyLayerCurrencyExchangeClient 클래스 등 위에 https://github.com/component를 다는 식으로 수정하는 것도 괜찮을거 같습니다 ㅎㅎ 의존성을 주입받는 부분 외에 특별히 빈등록 설정을 따로 빼야하는 커스텀 설정은 보이지 않아서요

하나의 주제에 관련되어있지만 퍼져있는 Bean들을 한 곳에서 알 수 있게 Configuration에서 등록하는건 어떻게 생각하시나요?

한편으로는 package로 할 수 있는 일을 잘못된 package 분리로 인해 Configuration로 해결하는 느낌이 들기도 하네요.

2023-09-01 11:22 UTC, whatasame commented on src/main/java/shopping/exchange/CurrencyLayerClient.java
> +public class CurrencyLayerClient {
어떤 것을 의미하는 지 잘 이해하지 못했습니다. method의 접근 제어자를 변경하란 말씀이신가요? 아니면 생성자인가요?

2023-09-05 13:18 UTC, sihyung92 approved these changes
안녕하세요 정규님~~!
요즘 다소 느슨해진 삶을 이어가고 있어서 리뷰가 늦었습니다 🙇‍♂️
몇가지 리뷰는 남겼지만 전체적으로 잘 반영해주셨고 미구현 요구사항도 마무리 잘해주셔서 머지하도록 하겠습니다 ㅎ
앞으로도 화이팅입니다~~~ 🙌

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/config/RestConfig.java
> +            .setReadTimeout(Duration.ofSeconds(1));
1. 물어본다 
    - API 명세에 적시되어 있는 내용을 찾아보는 것도 '물어본다'에 해당하는 거 같습니다 (99%의 응답은 1000ms내에 응답되는 것이 보장됩니다 같이..)
    - 그런데 API 명세에 이런 비기능적 내용까지 잘 적혀있는 경우가 많지 않아서요
    - 어느 상황에서 쓸건지, 어느정도의 호출량을 가져갈건지 계측한 후 물어보는게 최고입니다 
2. 실제 응답 속도를 본다
    - 그런데 물어봐도 정확한 대답을 얻기 어려울 때가 많아서요 (실제와 다를 때가 많음)
    - 이럴 땐 운영 환경에서 계측해보면서 적절한 값을 찾는 편입니다
    - 내가 만든 서비스라면 적절한 응답속도를 가질 수 있도록 쿼리튜닝이나 API 검토 등을 할 때가 많고요

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/cart/CartProduct.java
> +    private Product product;
요즈음엔 chat GPT 등이 잘 되있어서 남 괴롭힐 일 없이 검색하기 쉬운 세상이 되었어요 ㅎㅎ
최근 재밌게 본 블로그 입니다 

[입만 가지고 떠드는 개발자가 ChatGPT에게 외주줘서 만든 Mysql 복제지연 모니터링
](https://d2.naver.com/helloworld/8532139)

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/Order.java
> +import javax.persistence.*;
와일드카드 임포트가 있네요~~
인텔리제이 설정을 통해 와일드카드 임포트가 들어오지 않도록 조정할 수 있습니다
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/OrderProduct.java
> +
두줄 개행이 있네요 ㅎ

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/OrderProduct.java
> +    private ProductImage orderedImage;
OrderProductImage는 사용하지 않나요?

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/OrderProduct.java
> +public class OrderProduct {
VO 적극적인 활용이 좋네요 ㅎ

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/Order.java
> +        this.orderCurrencyRate = usdRate == null ? null : new OrderCurrencyRate(usdRate);
null 일 때 활용할 수 있는 1.0 currency rate 를 활용했어도 괜찮았을거 같아요
null 방어 코드가 필요없어지는 장점이 있어서요

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/domain/order/Order.java
> +        return this.orderCurrencyRate.getCurrencyRate();
바로 위 리뷰에서 언급한 부분인데, 해당 코드는 orderCurrencyRate가 null 일 경우 NPE가 발생합니다

2023-09-05 13:18 UTC, sihyung92 commented on src/test/java/shopping/auth/JwtResolverTest.java
> +        final String expired = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkxMDI5NjExLCJleHAiOjE2OTEwMjk2MTF9.g_8Dw3NjGGUz9Jn1jN5U-y2SL-a8nmVQeMr17d0NLjw";
어떤 payload인지 주석 등으로 표현하면 더 가독성 있는 테스트가 될거같아요 ㅎ

2023-09-05 13:18 UTC, sihyung92 commented on src/test/java/shopping/domain/order/OrderProductImageTest.java
> +
두 줄 개행!

2023-09-05 13:18 UTC, sihyung92 commented on src/test/java/shopping/domain/order/OrderProductImageTest.java
> +
여러 번 보이는거 보니 의도적으로 띄우시는거 같기도 하네요 ㅎ

2023-09-05 13:18 UTC, sihyung92 commented on src/test/java/shopping/exchange/CurrencyLayerCurrencyExchangerTest.java
> +    RestConfig.class})
ㅎㅎ;; 제가 출연하는 걸 까먹고 있었네요

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/exchange/CurrencyLayerCurrencyExchanger.java
> +    }
Optional 반환 인터페이스를 선택하셨고, 실제로 사용 코드 (OrderService)에서도 orElse 등으로 처리하고 있는 걸 감안하면 client 호출 과정에서 오류가 발생했을 때 `Optional.empty();` 를 반환하는 것도 방법일거 같아요.

이건 오류 제어를 어떻게 하고 싶은지에 따라 달라지는데, 환율 호출이 실패하면 즉시 감지되고 장애상황으로 간주해야 한다면 예외 throw를, 자연스럽게 처리되도록 하고싶다면 empty 반환을 선택하면 될거같아요.

적다보니 제3의 길로 client 호출 실패는 Throw, 응답받은 결과물에 "from",  "to" 에 해당하는 환율이 없다면 Optional.empty() 를 반환하는 방법도 있을거 같은데요, 
다만 현재 코드로서는 자연스럽게 되지는 않겠네요 (`exchangeRateByCurrency.get(from.getName() + to.getName())` 결과값이 null 일 때 오류가 발생하는 스타일이어서요)

2023-09-05 13:18 UTC, sihyung92 commented on src/main/java/shopping/config/ExchangeConfig.java
> +    }
configuration이 지나치게 비대해지는 문제점만 주의한다면 주제별로 모아주는 것도 괜찮다고 생각해요~
다만 이 주제는 그냥 order와 관련된 빈 모두를 모으는 게 아니라, 
DB 설정을 위한 bean 모음 / ObjectMapper 설정을 위한 bean 모음 등 기술적 분할을 적용한 경우에만 유효하다고 생각합니다. 
도메인으로 분할해서 몰아넣으면 클래스 내부가 정리 안 된 폴더 수준을 벗어나기 힘들거 같아서요 ㅎ

2023-09-05 13:18 UTC, merged