Step1, 2, 3 구현 완료하였습니다.
next-step/spring-shopping-old pull request #6
Opened 2023-08-03 07:19 UTC by bkRyusim

안녕하세요! 쇼핑 과제 리뷰 받게된 백승윤입니다. 항상 리뷰해주셔서 감사합니다 ㅎㅎ

## 신경 쓴 점
- 저번 미션까지 통합 테스트를 DirtiesContext로 항상 컨텍스트를 초기화 했었는데, 이번에는 컨텍스트는 한번만 초기화하고, DB만 초기화하도록 하여 테스트 시간을 짧게 유지했습니다.
- 패스워드를 암호화하여 저장할 수 있도록 하였습니다.
- 에러를 Enum 한 곳에 모아서 관리하였습니다.

## 질문
- POST 요청으로 장바구니 항목을 담는 엔드포인트가 있는데, 장바구니에 항목이 없으면 새로 CartItem을 생성하고, 장바구니에 이미 품목이 있으면 기존 CartItem의 Quantity를 업데이트하는 로직을 수행합니다. POST라는 한번의 메서드가 어쩔땐 생성 로직을 수행하고, 어쩔땐 수정 로직을 수행하는 것이 좋을까요? 아니면 POST 시 이미 아이템이 존재하면 오류를 반환하고, 다시 PUT 또는 PATCH 요청을 보내도록 유도하는 것이 좋을까요?

2023-08-04 12:23 UTC, begaonnuri requested changes
안녕하세요 승윤님, 요구사항을 잘 구현해주셨네요 👍🏻 
몇가지 코멘트 남겼는데 확인해주세요.

2023-08-04 12:23 UTC, begaonnuri commented on README.md
> +## Step 1. 상품
요구사항과 기능 목록을 잘 작성해주셨네요 👍🏻

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/AuthService.java
> +                .orElseThrow(() -> new ShoppingException(ErrorType.WRONG_LOGIN_REQUEST));
사용자가 `"잘못된 로그인 요청입니다."`를 보고 행동을 교정할 수 있을까요? 올바른 행동을 하도록 메시지를 변경하면 어떨까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/AuthService.java
> +    private final UserRepository userRepository;
인터페이스를 잘 활용해주셨네요 👍🏻

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/CartService.java
> +    private final UserRepository userRepository;
앞으로 생기는 모든 서비스는 UserRepository를 참조하게될 것 같아요. 게다가 이런 사용자 정보는 Service들의 관심사가 아닐 수 있습니다. 이 부분을 어떻게 해소할 수 있을까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/CartService.java
> +        if (items.contains(item)) {
큰 차이는 없지만 바로 위에서 `items`에 추가가 이루어지는데 굳이 필요한가 싶은 조건문이네요 😅

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/CartService.java
> +    public void update(final QuantityUpdateRequest request, final Long cartItemId, final Long userId) {
update가 모든 항목을 업데이트한다고 오해할 여지가 있으니 QuantityUpdateRequest 처럼 수량만 업데이트한다는 의미를 담아 변경하면 어떨까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/application/CartService.java
> +            throw new ShoppingException(ErrorType.USER_NOT_CONTAINS_ITEM, item.getId());
마찬가지로 더 상세한 예외 메시지로 변경하면 어떨까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/config/interceptor/AuthInterceptor.java
> +    private static final String AUTHENTICATION_HEADER = "Authorization";
인증(Authentication)과 인가(Authorization)는 다른 개념입니다. 이렇게 HTTP에서 제공되는 스펙을 사용자가 정의하면 혼란의 여지가 생기기도 하니 스프링에서 제공하는 `HttpHeaders.AUTHORIZATION`를 사용해도 좋을 것 같네요.

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/domain/cart/Quantity.java
> +    public final static Quantity ONE = new Quantity(1);
이 부분만 상수로 만들어주신 이유가 있을까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ShoppingException.class)
ShoppingException 이외의 예외가 발생하면 사용자가 스택 트레이스를 접하게 되지 않을까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/infrastructure/TokenProvider.java
> +package shopping.infrastructure;
인프라스트럭처 패키지에 두는 기준은 무엇이었나요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/ui/CartController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
사용자가 생성된 리소스 정보를 어떻게 알 수 있을까요?

2023-08-04 12:23 UTC, begaonnuri commented on src/main/java/shopping/ui/LoginController.java
> +    @PostMapping("/token")
사용자가 인증 방법을 알 필요가 있을까요? `/token`을 추가하신 이유는 무엇인가요?

2023-08-04 12:23 UTC, begaonnuri commented on src/test/java/shopping/dto/CartCreateRequestTest.java
> +class CartCreateRequestTest {
요청 DTO까지 꼼꼼하게 테스트해주셨녜요 👍🏻

2023-08-04 12:28 UTC, begaonnuri commented
https://github.com/next-step/spring-shopping/pull/6#issue-1834443270 에 대한 답변입니다.

Q. POST 요청으로 장바구니 항목을 담는 엔드포인트가 있는데, 장바구니에 항목이 없으면 새로 CartItem을 생성하고, 장바구니에 이미 품목이 있으면 기존 CartItem의 Quantity를 업데이트하는 로직을 수행합니다. POST라는 한번의 메서드가 어쩔땐 생성 로직을 수행하고, 어쩔땐 수정 로직을 수행하는 것이 좋을까요? 아니면 POST 시 이미 아이템이 존재하면 오류를 반환하고, 다시 PUT 또는 PATCH 요청을 보내도록 유도하는 것이 좋을까요?

A. UI에 따라 달라질 수 있는 부분이라고 생각해요. 그리고 일반적으론 프론트엔드 개발의 편의에 따라 동일하게 하기도, 나누기도 합니다.

2023-08-06 05:14 UTC, bkRyusim commented on src/main/java/shopping/application/AuthService.java
> +                .orElseThrow(() -> new ShoppingException(ErrorType.WRONG_LOGIN_REQUEST));
더 자세히 작성해 보도록 하겠습니다 ㅎㅎ

2023-08-06 06:17 UTC, bkRyusim commented on src/main/java/shopping/config/interceptor/AuthInterceptor.java
> +    private static final String AUTHENTICATION_HEADER = "Authorization";
적용해 보겠습니다!

2023-08-06 06:44 UTC, bkRyusim commented on src/main/java/shopping/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ShoppingException.class)
앗 이외 예외들에 대한 핸들러도 작성하겠습니다!

2023-08-06 08:41 UTC, bkRyusim commented on src/main/java/shopping/application/CartService.java
> +        if (items.contains(item)) {
add 메서드는 같은 product가 존재하지 않는 경우 배열의 새 요소에 item을 추가하고, 이미 Product가 존재하는 경우에는 기존 CartItem의 Quantity를 1 추가하느 동작을 수행 중입니다. 그렇기 때문에 contain하는지에 대한 검증이 필요했던 건데, 이렇게 보니 코드 가독성이 좋은 것 같지 않아 메서드 이름과 동작 분리에 대해 조금 더 고민해 보도록 하겠습니다!

2023-08-06 08:45 UTC, bkRyusim commented on src/main/java/shopping/application/CartService.java
> +    private final UserRepository userRepository;
CartItem이 User의 id만 가지고 간접 참조 하는 방법이 있을 것 같습니다. 사실 간접 참조를 사용하려다 Product를 간접 참조하게 되면 Response DTO를 만들 때 등, 사용할 때 불편함과 성능상 불이익을 느껴 직접 참조하도록 하였습니다. User만 id로 참조하고 Product는 직접 참조하는 방식은 간접참조와 직접참조가 섞여 혼란스러워 질 수 있다는 점이 단점일 것 같았는데, 그렇게라도 하는 편이 더 나았을까요?

2023-08-06 08:47 UTC, bkRyusim commented on src/main/java/shopping/domain/cart/Quantity.java
> +    public final static Quantity ONE = new Quantity(1);
다른 프로젝트(조영호님 우아한 객체지향 강의 예제 eternity-oop)에서 이런 식으로 단위 인스턴스를 static으로 선언하는 것을 보고, 어떤 이점이 있을지 궁금해 한번 적용해 보았는데, 지금의 경우는 Quantity 객체에 정의하기보다는 CartItems 객체에 생성 초기 수량 값의 의미로 INITIAL_QUANTITY를 정의하는 편이 나았을 것 같습니다.

2023-08-06 10:47 UTC, bkRyusim commented on src/main/java/shopping/infrastructure/TokenProvider.java
> +package shopping.infrastructure;
외부 라이브러리를 사용하는 클래스들을 인프라스트럭처 패키지에 두었습니다. 이렇게 했더니 domain 패키지가 infrastructure 패키지에 의존하는 단점이 있네요. 인터페이스를 도메인 패키지에 적절히 옮겨 의존성 역전을 해보겠습니다.

2023-08-06 10:49 UTC, bkRyusim commented on src/main/java/shopping/ui/CartController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
헤더의 Location을 통해 리소스 정보를 알려줄 수 있겠지만, 요구사항에 1개 CartItem에 대한 GET 요청 endpoint가 존재하지 않아 Location을 반환하지 않았습니다. 피드백 반영하면서 엔드포인트와 Location을 한번 추가해 보겠습니다!

2023-08-06 18:07 UTC, bkRyusim commented
안녕하세요 리뷰가 조금 늦었습니다 ㅠㅠ 항상 리뷰해 주셔서 감사합니다😊

### 수정 사항
- Shoppingexception 외의 예외들을 핸들링하는 핸들러를 추가하고, 몇몇 예외 메시지를 구체적으로 변경하였습니다.
- 인터페이스를 분리해 더이상 domain 패키지가 infrastructure 패키지를 의존하지 않습니다.
- CartItem이 User를 Id로 간접 참조하여 더이상 CartService가 UserRepository를 의존하지 않습니다.
- CartItem을 추가하는 엔드포인트의 헤더 Location에 결과를 확인할 수 있는 자원 주소를 반환하며, 해당 자원을 확인할 수 있는 GET 엔드포인트를 추가하였습니다.
- 그 외 몇몇 네이밍 및 부적절한 상수 선언들을 변경하였습니다.

2023-08-07 16:01 UTC, begaonnuri commented on src/main/java/shopping/application/AuthService.java
> +import shopping.domain.user.UserRepository;
리뷰를 잘 이해해주시고 의존성을 역전 시켜주셨네요 👍🏻

2023-08-07 16:01 UTC, begaonnuri commented on src/main/java/shopping/application/TokenProvider.java
> +package shopping.application;
TokenProvider를 application 패키지에 두신 이유가 있을까요?

2023-08-07 16:01 UTC, begaonnuri commented on src/main/java/shopping/domain/cart/Quantity.java
> +    public final static Quantity ONE = new Quantity(1);
잘 해주셨는데 `ONE`만 static으로 만들어주신게 의아했어요. Integer 클래스같은 경우 자주 참조되는 숫자들을 이너 클래스로 캐싱해두기도 하는데요, 장바구니 수량도 이를 고려해서 적절한 숫자를 캐싱해두면 어떨까요?

2023-08-07 16:10 UTC, begaonnuri approved these changes
안녕하세요 승윤님. 리뷰 잘 반영해주셨네요!
이번 단계는 여기서 머지하겠습니다. 고생하셨습니다.

몇가지 코멘트도 남겼는데 확인해주세요!

2023-08-07 16:10 UTC, begaonnuri commented on src/main/java/shopping/ui/AuthenticationPrincipalArgumentResolver.java
> +public class AuthenticationPrincipalArgumentResolver implements HandlerMethodArgumentResolver {
ArgumentResolver는 ui 패키지에 속해있고 Interceptor는 config 패키지에 속해있네요. 구분하신 기준이 있었을까요?

2023-08-07 16:10 UTC, begaonnuri commented on src/main/java/shopping/application/CartService.java
> +    private final UserRepository userRepository;
간접 참조 하는 경우와 직접 참조하는 경우 어떤 장단점이 있다고 생각하시나요?

지금도 잘 해주셨지만 반대로 직접 참조를 유지하면서 ArgumentResolver에서 userId가 아닌 완성된 User를 반환해주는 방법도 있을 것 같아요.

2023-08-07 16:11 UTC, merged

2023-08-08 01:55 UTC, bkRyusim commented on src/main/java/shopping/application/TokenProvider.java
> +package shopping.application;
원래 AuthService에서 JwtManager를 의존하고 있었는데, 의존성 역전을 위해 Provider 인터이스를 정의해 같은 패키지에 위치했습니다. 생성 로직을 도메인 서비스로 옮기고 도메인 패키지에서 의존하는 편이 더 나을까요?

2023-08-08 01:59 UTC, bkRyusim commented on src/main/java/shopping/ui/AuthenticationPrincipalArgumentResolver.java
> +public class AuthenticationPrincipalArgumentResolver implements HandlerMethodArgumentResolver {
AuthenticationPrincipal 어노테이션과 ArgumentResolver 클래스가 동일 패키지에 위치하되, controller 패키지가 config 패키지를 의존하지 않기 위해 ui 패키지에 둘을 함꼐 위치시켰습니다. 지금 생각해 보니 어노테이션은 그대로 두고 ArgumentResolver는 config에 두어도 될 것 같습니다.