Step1, Step2, Step3: 쇼핑
next-step/spring-shopping-old pull request #9
Opened 2023-08-03 10:13 UTC by ProtoSeo

안녕하세요. 우아한테크캠프 6기 서승훈입니다.
네 번째 미션 Spring쇼핑의 1, 2, 3단계 미션에 대한 Pull request입니다.

## 구현한 부분

### Step1 상품

- 상품 목록 페이지 연동

### Step2 사용자 / 로그인

- 사용자 도메인 구현
- 로그인 기능 구현
- 로그인 페이지 연동

### Step3 장바구니 기능 구현

- 장바구니 아이템 도메인 구현
- 장바구니 아이템 생성, 수정, 삭제기능 및 목록 기능 구현
- 장바구니 페이지 연동

2023-08-04 05:01 UTC, fucct requested changes
안녕하세요. 

전체적으로 깔끔하게 레이어 구분하고 작성해주신것 같아요.
제가 리뷰하는 다른 분과 코드의 형태가 비슷한데, 혹시 페어시면 리뷰어를 바꿔달라고 요청해보셔도 괜찮을것 같습니다. 다양한분께 리뷰를 받는게 더 좋을 수 있거든요
(https://github.com/next-step/spring-shopping/pull/5)
간단하게 코멘트 남겨드렸으니 확인해보시고 이해되지 않는 부분이 있다면 질문주세요!

2023-08-04 05:01 UTC, fucct commented on docker-compose.yml
> +version: "3.8"
요구사항에 docker도 있었나요!?

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/repository/CartItemRepository.java
> +    @EntityGraph(attributePaths = {"product", "member"})
EntityGraph를 사용하신 이유를 설명해주실 수 있으신가요?

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/domain/member/Email.java
> +        validate(value);
DB에 들어가는값에 정규식 검사와 같은 검증이 들어있으면, 매번 엔티티가 조회되고 저장될때마다 해당 검증이 들어가게 되어 CPU리소스 낭비가 있을 수 있습니다. 따라서 검증 후에 저장시에는 String으로 저장하는것도 하나의 방법이 될 수 있어요.

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secretKey)
JWT를 사용하실때 secretKey를 고정값으로 사용하시면, 탈취되었을때 발급된 모든 액세스토큰을 신뢰할 수 없게 됩니다.

따라서 secretKey는 순환될 수 있는형태로 작성해주시는게 좋습니다.
payload에 secretKey에 대한 버전정보를 함께 기록하시면 좋습니다

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .getSubject();
registered Claim인 subject는 토큰의 제목에 해당하는 항목이에요.
저희가 기록하고자하는 커스텀한 claim들은 put을 통해 key-value 쌍으로 넣어주는건 어떨까요?

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/exception/ErrorCode.java
> +public enum ErrorCode {
이런식으로 관리되는것은 위험할 수 있어요.

일단 우리가 정의하지 않은 예외가 발생했을때 처리할 수 있는 handler가 없다는 문제가 있습니다. (ex. DB 연결 실패, Query 오류 등 )

또한 예외 메세지/예외 코드는 애플리케이션마다 다른 형태로 반환되어야 하는 경우가 있어요. 특히 예외 메세지가 어떤경우엔 상세하게 내려가야하지만, 어떤 경우엔 단순한 예외로 응답해야하는 경우가 있습니다.

다만 ErrorType과 같은 정의는 괜찮은것 같습니다. 현업에서는 예외 상황에 따른 프론트의 행위를 결정하기 위해 이런 코드화된 응답을 내리기도 합니다. 따라서 예외 상황에 맞는 응답을 설계하고, 그에 대한 예외메세지와 상태가 아닌, 해당 코드를 내려보는건 어떨까 싶네요!

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/controller/CartItemController.java
> +    public ResponseEntity<CartItemResponses> readCartItems(@RequestAttribute final Long loginMemberId) {
ArgumentResolver를 사용하시지 않으셨네요 :) 
적용해달라는 의미는 아니고, 왜 적용하지 않으셨는지 궁금합니다!

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/service/CartItemService.java
> +        return CartItemResponse.from(cartItem);
여기까지 쿼리가 굉장히 많이 발생하고있는데요.
memberId에 속한 List<cartItem> 를 불러와서 carItem중 productId에 해당하는 녀석을 +1 하면 되는데, 모든걸 쿼리로 수행하고 있네요.

Java 코드로 수행할 수 있을것 같은데 한번 바꿔볼까요?

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/service/CartItemService.java
> +        cartItem.validateMember(member);
```java
cartItemRepository.findById(cartItemId)
    .filter(멤버일치여부검증)
    .orElseThrow(() -> new ShoppingException(ErrorCode.NOT_FOUND_CART_ITEM_ID));
```

이런식으로 가능합니다 ㅎㅎ

2023-08-04 05:01 UTC, fucct commented on src/main/java/shopping/service/CartItemService.java
> +public class CartItemService {
Service에 대한 테스트도 작성해주세요.

2023-08-04 15:31 UTC, ProtoSeo commented on docker-compose.yml
> +version: "3.8"
요구사항에 도커가 있었던 것은 아니에요! 저희가 개발할 때 프로덕션환경에서 로컬 데이터베이스를 사용하기 위해 사용했습니다.

처음에 개발할 때, `data.sql`과 `schema.sql` 을 `main/resources` 에 두고 개발을 하고 있었는데요, 계속 미션을 진행하면서 테스트를 작성할 때 `main/resources` 에 속한 `data.sql`, `schema.sql` 에 의존하는 테스트를 짜게 된다는 생각이 들어서 `data.sql`과 `schema.sql`은 `test/resources`로 옮기고, 프로덕션에서는 로컬 데이터베이스를 사용하려고 했습니다.

2023-08-07 00:46 UTC, ProtoSeo commented on src/main/java/shopping/repository/CartItemRepository.java
> +    @EntityGraph(attributePaths = {"product", "member"})
EntityGraph를 사용한 이유는, `CartItemRepository`에서 `CartItem`을 꺼내서 사용할 때, `CartItem`이 가지고 있는 `Product`와 `Member`의 정보를 같이 사용하는데요, 이 때 `CartItem`에서 `Product`와 `Member`의 `FetchType`이 `Lazy`여서 `Product`와 `Member`를 사용할 때 `select` 쿼리가 추가적으로 발생하는 것을 막기 위해서 다 조인해서 가져오려고 사용했어요.

지금 생각해보니 다른 사람이 저희 코드를 사용하면서 `findById`를 사용할 때에, 이렇게 조인이 걸릴 것이라는 것을 생각하지 못할 수 있을 것 같아요. 그래서 `@EntityGraph`를 사용하는 메서드는 따로 분리하고 `findById`는 원래 JpaRepository 인터페이스가 제공해주는 것대로 사용하는 것이 좋을 것 같아요!

2023-08-07 00:54 UTC, ProtoSeo commented on src/main/java/shopping/service/CartItemService.java
> +        cartItem.validateMember(member);
아하! `Optional`에서도 `filter`를 사용할 수 있네요! 이렇게 하면 `deleteCartItem`, `updateCartItem` 에서 `validateMember` 해주면서 발생하는 코드 중복을 제거할 수 있을 것 같아서 적용했습니다!

2023-08-07 05:53 UTC, ProtoSeo commented on src/main/java/shopping/domain/member/Email.java
> +        validate(value);
제가 이해한 게 맞는지 여쭤보고 싶은데요,

```java
Member member = memberRepository.findById(MEMBER_ID).orElseThrow(...);
```
다음과 같은 코드가 있다고 할 때, `Member` 객체를 생성하기 위해서 `Email` 객체 등등도 같이 생성되면서 `Email` 생성자의 `validate()`를 통과하게 되고 그로 인해서 정규 표현식 검사와 같은 일 때문에 리소스 낭비가 있을 수 있다는 것이죠?

이렇게 동작하게 되면, 매번 `Member` 객체를 필요로 하는 곳에서 생성될 때 마다 `Email`, `Password`에서 검증을 해야 하니까, 실제로 CPU 리소스 낭비가 발생할 수 있을 것 같아요! 

근데 계속 고민이 됐던 부분은 `CPU 리소스 낭비가 발생한다` 라는 관점에서 보면 코드를 수정하는 것이 맞는 것 같은데, 제가 처음에 원시값을 포장했던 이유(각 객체가 할 일을 더 구체적으로 표현하기 위함)에 따르면 이제는 `Member`에서 원시값 자체를 들고 있기 때문에 표현력이 떨어지지 않을까? 하는 고민이 되긴 해요. 

그래서 일단은 `Member`에 대해서만 원시값 포장한 것들에 대해서만 검증 후에 저장 시 `String`으로 저장하도록 수정했습니다. (이 부분만 수정한 이유는 다른 `Product`나 `CartItem`에서 검증하는 부분들에 대해서는 정규표현식을 사용해서 검증하는 것이 아니라서 엄청 자원을 잡아먹지는 않을 것 같다고 생각했어요)

2023-08-07 06:37 UTC, ProtoSeo commented on src/main/java/shopping/exception/ErrorCode.java
> +public enum ErrorCode {
아하! 맞네요! 지금은 `ShoppingException` 관련 예외만 처리하고 있네요.

`ErrorCode` 가 현재 `ShoppingException` 관련만 처리하고 있어서 `ShoppingErrorType`으로 수정했습니다. 그리고 `ShoppingExceptionHandler`는 `CommonExceptionHandler`로 수정하고, `SQLException`을 핸들링할 수 있도록 추가했습니다!

2023-08-07 07:19 UTC, ProtoSeo commented on src/main/java/shopping/service/CartItemService.java
> +        return CartItemResponse.from(cartItem);
이미 장바구니에 담겨져 있는 경우에는 5번 정도의 쿼리가 나가고 있네요!

`cartItemRepository.findAllByMemberId(memberId)` 를 활용해서 해당 회원이 가지고 있는 `CartItem` 을 불러 온 다음, 해당 product가 있는지 확인 후 존재한다면 +1 하도록 수정했습니다.

2023-08-07 07:49 UTC, ProtoSeo commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secretKey)
아하! 토큰이 탈취되면 그런 일이 발생할 수 있을 것 같아요! 탈취되는 경우에 대해서는 생각해보지 못한 것 같아요~

이 부분에 대해서 코드를 반영해보고 싶은데, _`따라서 secretKey는 순환될 수 있는형태로 작성해주시는게 좋습니다.`_ 이 부분을 어떻게 구현할 지 고민이 됩니다!

`application.yml` 에서 여러 `secretKey`를 정의하고 이를 `JwtTokenProvider` 에서 불러와서 여러 개의 `secretKey`를 매번 다르게 할당해주면 되는 것인지, 그렇게 구현한다면 JWT를 파싱할 때 어떤 `secretKey`를 써야 하는 걸 알 수 있을지 궁금해요. 아니면 다른 방법이 있는지..? 

혹시 힌트 조금 주실 수 있으신가요..?

2023-08-07 08:04 UTC, ProtoSeo commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .getSubject();
현재 JWT에 담기는 정보가 `sub`, `iat`, `exp` 밖에 없어서 메서드 명은 `getPayload`지만 `Claims`에서 `getSubject`를 했던 것 같아요. JWT에 추가적으로 따로 담아줄 `claim`값이 존재하지 않고, 지금은 `subject` 값만 사용하고 있기 때문에 이렇게 사용하는 것도 괜찮지 않을까 생각합니다!

지금 생각에 메서드 명이 너무 포괄적인 의미인 것 같아서, `getSubject`로 메서드 명을 변경했습니다.

2023-08-07 08:09 UTC, ProtoSeo commented on src/main/java/shopping/controller/CartItemController.java
> +    public ResponseEntity<CartItemResponses> readCartItems(@RequestAttribute final Long loginMemberId) {
현재 요구사항에서 Interceptor에서 인증 후 필요한 정보가 `memberId` 밖에 없다고 생각했어요. 그래서 `memberId`만 꺼내서 넘겨줘도 되지 않을까 생각해서 ArgumentResolver를 사용하지 않았습니다.

만약 추가적으로 회원의 등급이나, 회원의 권한 같은 정보들이 토큰에 담겨있고, Controller에서 이런 정보들이 필요했다면 Interceptor에서 토큰을 사용해 `LoginMember`와 같은 인증받은 후의 회원 객체를 만들고, 이 객체에 대한 ArgumentResolver를 작성해서 사용했을 것 같아요!

2023-08-07 09:50 UTC, ProtoSeo commented on src/main/java/shopping/service/CartItemService.java
> +public class CartItemService {
[cedb34d](https://github.com/next-step/spring-shopping/pull/9/commits/cedb34d0fd91c374c1ea72e3784cc54067223806) 

Service 계층 테스트 추가했습니다!

2023-08-07 09:56 UTC, ProtoSeo commented
> 제가 리뷰하는 다른 분과 코드의 형태가 비슷한데, 혹시 페어시면 리뷰어를 바꿔달라고 요청해보셔도 괜찮을것 같습니다. 다양한분께 리뷰를 받는게 더 좋을 수 있거든요

페어는 아닌데, 우연치 않게 코드가 비슷한 것 같습니다! 신기하네요ㅎㅎ

2023-08-08 12:47 UTC, fucct commented on docker-compose.yml
> +version: "3.8"
좋은 시도이신것 같습니다!

2023-08-08 12:49 UTC, fucct commented on src/main/java/shopping/repository/CartItemRepository.java
> +    @EntityGraph(attributePaths = {"product", "member"})
굳이 변경해주지 않으셔도 되는데 ㅎㅎ 궁금해서 여쭤봤습니다.
좀 더 학습을 해보고 싶으시다면 QueryDSL을 사용하는법도 익혀보시면 좋을것 같아요! 
java코드로 SQL 쿼리를 짜듯이 자유롭게 Join을 할 수 있는 방법중 하나거든요! 

다만 이번 미션에선 반영 안해주셔도 괜찮습니다!

2023-08-08 12:51 UTC, fucct commented on src/main/java/shopping/domain/member/Email.java
> +        validate(value);
깊게 고민해보신게 느껴지는 코멘트입니다. 

시스템을 운영할때도 매번 고민하는 부분인데요. 사실 리소스를 조금 사용하더라도 온전한 값을 보장해주는게 중요할 수도 있습니다. 
다만 이런 경우에 골머리를 썩었던것 같아요. VO를 엔티티에 적용하면서 검증로직도 넣어놨는데, 예전의 데이터들은 그 검증로직에 부합하지 않는 경우이죠. 

레거시들이 쌓여감에 따라서, VO를 점차 걷어냈던 경험도 있어서.. 이런부분은 한번씩 신중하게 고민해보시면 좋겠다는 마음으로 의견을 드렸습니다! 지금은 말씀하신 정도로만 변경해주셔도 문제없어보입니다!

2023-08-08 12:54 UTC, fucct commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .signWith(SignatureAlgorithm.HS256, secretKey)
JWT를 너무 딥하게 코멘트드린게 아닌가 걱정스럽기도 한데요 ㅎㅎ
JWT의 claim안에 version과 같은 값을 함께 넣어주는 방식은 어떨까 싶어요

ex)"1"버전일때는 A라는 secret Key 사용, "2"버전일때는 B라는 secret Key 사용 ...

이런식으로 하면, version별로 사용하는 secretKey를 관리하면서, 특정 버전의 토큰을 신뢰할지 안할지도 결정할 수 있게 됩니다.

이 부분은 설계하기 나름이고, 이번 미션에서 중요 포인트는 아니기 때문에 고민만 해보셔도 괜찮을것 같습니다!

2023-08-08 12:55 UTC, fucct commented on src/main/java/shopping/auth/JwtTokenProvider.java
> +                .getSubject();
넵! JWT의 registered Claim들이 의미하는 바를 한번 숙지해보시면 좋을것 같아요.

아래 블로그에 나와있는 내용을 기반으로 보면, subject는 토큰의 이름 같은 claim 입니다 ㅎㅎ

<img width="830" alt="image" src="https://github.com/next-step/spring-shopping/assets/48818566/d14e4c28-f1fa-47a8-89e6-479ffa9cbb32">
https://velog.io/@maintain0404/JWT%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90

2023-08-08 12:57 UTC, fucct commented on src/main/java/shopping/exception/ErrorCode.java
> +public enum ErrorCode {
일반 Exception도 반드시 잡아주셔야 해요 ㅎㅎ. 이런경우 어떤메세지를 내리는지도 굉장히 중요한 문제입니다.

사용자에게 시스템 내부를 노출하는 예외메세지가 응답되면 시스템의 취약점을 해커들에게 제공해주는 꼴이 되거든요.
그래서 Internal Server Error같은 상황은 웬만하면 "응답에 실패했습니다" 와 같은 단순한 메세지를 응답하고, 서버상에서 로그를 상세하게 찍어서 디버깅을 하는 편입니다!

2023-08-08 12:59 UTC, fucct commented on src/main/java/shopping/controller/CartItemController.java
> +    public ResponseEntity<CartItemResponses> readCartItems(@RequestAttribute final Long loginMemberId) {
본인이 선택한 선택지에 대한 의견이 명확해서 좋네요! 항상 어떠한 선택을 하실때는 왜 그렇게 했는지를 명확하게 기억해주시는게 중요합니다!

2023-08-08 13:02 UTC, fucct approved these changes
안녕하세요!

리뷰반영 과정에서 고민을 많이 하고 반영해주신게 느껴져서 인상깊었습니다 :) 
각각 코멘트 드렸으니, 한번 확인해보시고 고민해보시면 좋을것 같습니다. 
그리고 리뷰반영 하신 부분을 커밋링크를 다 달아주셨던데 ㅎㅎ 번거로우시다면 꼭 그렇게 안해주셔도 괜찮습니다. (그런부분을 찾아서 보는것도 제 역할과 책임이여서 괜찮습니다. 😊)

코멘트 달아드린 부분은 반영을 해달라는 의미는 아니였고, 고민해보시고 선택적으로 반영해주시면 될 것 같아요. (다음 리뷰때 반영해주신 부분은 코멘트에 알려주세요!)

수고많으셨습니다!

2023-08-08 13:02 UTC, merged